//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace com.Sconit.Service.SAP.MI_PO_BOM_LES {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MI_PO_BOM_LESBinding", Namespace="http://www.sih.cq.cn/sap/pp/02")]
    public partial class MI_PO_BOM_LESService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MI_PO_BOM_LESOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MI_PO_BOM_LESService() {
            this.Url = global::com.Sconit.Service.SAP.Properties.Settings.Default.com_Sconit_Service_SAP_MI_PO_BOM_LES_MI_PO_BOM_LESService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MI_PO_BOM_LESCompletedEventHandler MI_PO_BOM_LESCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", RequestElementName="ZSIH_GETORDERBOMDETAIL", RequestNamespace="urn:sap-com:document:sap:rfc:functions", ResponseElementName="ZSIH_GETORDERBOMDETAIL.Response", ResponseNamespace="urn:sap-com:document:sap:rfc:functions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("OUTPUT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSPOBOM[] MI_PO_BOM_LES([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string INPUT) {
            object[] results = this.Invoke("MI_PO_BOM_LES", new object[] {
                        INPUT});
            return ((ZSPOBOM[])(results[0]));
        }
        
        /// <remarks/>
        public void MI_PO_BOM_LESAsync(string INPUT) {
            this.MI_PO_BOM_LESAsync(INPUT, null);
        }
        
        /// <remarks/>
        public void MI_PO_BOM_LESAsync(string INPUT, object userState) {
            if ((this.MI_PO_BOM_LESOperationCompleted == null)) {
                this.MI_PO_BOM_LESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMI_PO_BOM_LESOperationCompleted);
            }
            this.InvokeAsync("MI_PO_BOM_LES", new object[] {
                        INPUT}, this.MI_PO_BOM_LESOperationCompleted, userState);
        }
        
        private void OnMI_PO_BOM_LESOperationCompleted(object arg) {
            if ((this.MI_PO_BOM_LESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MI_PO_BOM_LESCompleted(this, new MI_PO_BOM_LESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSPOBOM {
        
        private string aUFNRField;
        
        private string oRDER_MATERIALField;
        
        private string mATERIALField;
        
        private string bISMTField;
        
        private string mAKTXField;
        
        private string bASE_UOMField;
        
        private decimal rEQ_QUANField;
        
        private bool rEQ_QUANFieldSpecified;
        
        private string sTORAGE_LOCATIONField;
        
        private string sEQUENCEField;
        
        private string oPERATIONField;
        
        private string wORK_CENTERField;
        
        private string rESERVATION_NUMBERField;
        
        private string rESERVATION_ITEMField;
        
        private string bESKZField;
        
        private string sOBSLField;
        
        private string gwField;
        
        private string wzField;
        
        private string zOPIDField;
        
        private string zOPDSField;
        
        private string lIFNRField;
        
        private string iCHARGField;
        
        private string bWARTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AUFNR {
            get {
                return this.aUFNRField;
            }
            set {
                this.aUFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORDER_MATERIAL {
            get {
                return this.oRDER_MATERIALField;
            }
            set {
                this.oRDER_MATERIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BISMT {
            get {
                return this.bISMTField;
            }
            set {
                this.bISMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MAKTX {
            get {
                return this.mAKTXField;
            }
            set {
                this.mAKTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BASE_UOM {
            get {
                return this.bASE_UOMField;
            }
            set {
                this.bASE_UOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal REQ_QUAN {
            get {
                return this.rEQ_QUANField;
            }
            set {
                this.rEQ_QUANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REQ_QUANSpecified {
            get {
                return this.rEQ_QUANFieldSpecified;
            }
            set {
                this.rEQ_QUANFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STORAGE_LOCATION {
            get {
                return this.sTORAGE_LOCATIONField;
            }
            set {
                this.sTORAGE_LOCATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SEQUENCE {
            get {
                return this.sEQUENCEField;
            }
            set {
                this.sEQUENCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPERATION {
            get {
                return this.oPERATIONField;
            }
            set {
                this.oPERATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WORK_CENTER {
            get {
                return this.wORK_CENTERField;
            }
            set {
                this.wORK_CENTERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVATION_NUMBER {
            get {
                return this.rESERVATION_NUMBERField;
            }
            set {
                this.rESERVATION_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVATION_ITEM {
            get {
                return this.rESERVATION_ITEMField;
            }
            set {
                this.rESERVATION_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BESKZ {
            get {
                return this.bESKZField;
            }
            set {
                this.bESKZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SOBSL {
            get {
                return this.sOBSLField;
            }
            set {
                this.sOBSLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GW {
            get {
                return this.gwField;
            }
            set {
                this.gwField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WZ {
            get {
                return this.wzField;
            }
            set {
                this.wzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZOPID {
            get {
                return this.zOPIDField;
            }
            set {
                this.zOPIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZOPDS {
            get {
                return this.zOPDSField;
            }
            set {
                this.zOPDSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ICHARG {
            get {
                return this.iCHARGField;
            }
            set {
                this.iCHARGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BWART {
            get {
                return this.bWARTField;
            }
            set {
                this.bWARTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MI_PO_BOM_LESCompletedEventHandler(object sender, MI_PO_BOM_LESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MI_PO_BOM_LESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MI_PO_BOM_LESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZSPOBOM[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZSPOBOM[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591