ALTER TABLE [dbo].[ACC_Permission]
    ADD CONSTRAINT [FK_ACC_PERM_REFERENCE_ACC_PERM2] FOREIGN KEY ([Category]) REFERENCES [dbo].[ACC_PermissionCategory] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

