ALTER TABLE [dbo].[ACC_RolePermission]
    ADD CONSTRAINT [FK_ACC_ROLE_REFERENCE_ACC_PERM2] FOREIGN KEY ([PermissionId]) REFERENCES [dbo].[ACC_Permission] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

