ALTER TABLE [dbo].[ACC_UserPermissionGroup]
    ADD CONSTRAINT [FK_ACC_USER_REFERENCE_ACC_PERM2] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[ACC_PermissionGroup] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

