ALTER TABLE [dbo].[ACC_RolePermissionGroup]
    ADD CONSTRAINT [FK_ACC_ROLE_REFERENCE_ACC_PERM] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[ACC_PermissionGroup] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

