ALTER TABLE [dbo].[ACC_PermissionGroupPermission]
    ADD CONSTRAINT [FK_ACC_PERM_REFERENCE_ACC_PERM3] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[ACC_PermissionGroup] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

