ALTER TABLE [dbo].[BIL_PriceListDet]
    ADD CONSTRAINT [FK_BIL_PRIC_REFERENCE_BIL_PRIC] FOREIGN KEY ([PriceList]) REFERENCES [dbo].[BIL_PriceListMstr] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

