ALTER TABLE [dbo].[INV_StockTakeItem]
    ADD CONSTRAINT [FK_INV_STOC_REFERENCE_INV_STOC4] FOREIGN KEY ([StNo]) REFERENCES [dbo].[INV_StockTakeMstr] ([StNo]) ON DELETE NO ACTION ON UPDATE NO ACTION;

