ALTER TABLE [dbo].[INP_InspectMstr]
    ADD CONSTRAINT [FK_INP_INSP_REFERENCE_MD_PARTY2] FOREIGN KEY ([ManufactureParty]) REFERENCES [dbo].[MD_Party] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

