ALTER TABLE [dbo].[INV_ContLocationDet]
    ADD CONSTRAINT [FK_INV_CONT_REFERENCE_MD_CONTA] FOREIGN KEY ([Container]) REFERENCES [dbo].[MD_Container] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

