ALTER TABLE [dbo].[INV_LocationLotDet_6]
    ADD CONSTRAINT [FK_INV_LocationLotDet6_HuId_REFERENCE_INV_Hu_HuId] FOREIGN KEY ([HuId]) REFERENCES [dbo].[INV_Hu] ([HuId]) ON DELETE NO ACTION ON UPDATE NO ACTION;

