ALTER TABLE [dbo].[ISS_IssueTypeToMstr]
    ADD CONSTRAINT [FK_ISS_ISSU_REFERENCE_ISS_ISSU3] FOREIGN KEY ([IssueType]) REFERENCES [dbo].[ISS_IssueType] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

