ALTER TABLE [dbo].[INV_StockTakeResult]
    ADD CONSTRAINT [FK_INV_STOC_REFERENCE_INV_STOC3] FOREIGN KEY ([StNo]) REFERENCES [dbo].[INV_StockTakeMstr] ([StNo]) ON DELETE NO ACTION ON UPDATE NO ACTION;

