ALTER TABLE [dbo].[INV_ItemExchange]
    ADD CONSTRAINT [FK_INV_ITEM_REFERENCE_MD_LOCAT2] FOREIGN KEY ([LocationFrom]) REFERENCES [dbo].[MD_Location] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

