ALTER TABLE [dbo].[INV_LocationLotDet]
    ADD CONSTRAINT [FK_INV_LOCA_0_REFERENCE_MD_LOCAT2] FOREIGN KEY ([Location]) REFERENCES [dbo].[MD_Location] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

