ALTER TABLE [dbo].[ISS_IssueTypeToUserDet]
    ADD CONSTRAINT [FK_ISS_ISSU_REFERENCE_ISS_ISSU5] FOREIGN KEY ([IssueTypeTo]) REFERENCES [dbo].[ISS_IssueTypeToMstr] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

