ALTER TABLE [dbo].[INP_ProdScanDet]
    ADD CONSTRAINT [FK_INP_PROD_REFERENCE_INP_PROD] FOREIGN KEY ([ProdScan]) REFERENCES [dbo].[INP_ProdScanMstr] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

