ALTER TABLE [dbo].[INV_KanBanCardInfo]
    ADD CONSTRAINT [FK_INV_KANB_REFERENCE_INV_KANB] FOREIGN KEY ([KBICode]) REFERENCES [dbo].[INV_KanBanCard] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

