ALTER TABLE [dbo].[INP_RejectDet]
    ADD CONSTRAINT [FK_INP_REJE_REFERENCE_INP_INSP2] FOREIGN KEY ([InspResultId]) REFERENCES [dbo].[INP_InspectResult] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

