ALTER TABLE [dbo].[INV_LocationLotDet_16]
    ADD CONSTRAINT [FK_INV_LocationLotDet16_HuId_REFERENCE_INV_Hu_HuId] FOREIGN KEY ([HuId]) REFERENCES [dbo].[INV_Hu] ([HuId]) ON DELETE NO ACTION ON UPDATE NO ACTION;

