ALTER TABLE [dbo].[INP_InspectDet]
    ADD CONSTRAINT [FK_INP_INSP_REFERENCE_MD_LOCAT5] FOREIGN KEY ([ManufactureParty]) REFERENCES [dbo].[MD_Location] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

