ALTER TABLE [dbo].[INV_ContLocationDet]
    ADD CONSTRAINT [FK_INV_CONT_REFERENCE_INV_CONT] FOREIGN KEY ([ContId]) REFERENCES [dbo].[INV_ContainerDet] ([ContId]) ON DELETE NO ACTION ON UPDATE NO ACTION;

