ALTER TABLE [dbo].[ISS_IssueTypeToMstr]
    ADD CONSTRAINT [FK_ISS_ISSU_REFERENCE_ISS_ISSU4] FOREIGN KEY ([IssueLevel]) REFERENCES [dbo].[ISS_IssueLevel] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

