ALTER TABLE [dbo].[INP_ConcessionDet]
    ADD CONSTRAINT [FK_INP_CONC_REFERENCE_INP_CONC] FOREIGN KEY ([CCSNo]) REFERENCES [dbo].[INP_ConcessionMstr] ([CCSNo]) ON DELETE NO ACTION ON UPDATE NO ACTION;

