ALTER TABLE [dbo].[ORD_OrderBackflushDet]
    ADD CONSTRAINT [FK_ORD_ORDE_REFERENCE_SCM_PROD2] FOREIGN KEY ([ProdLineFact]) REFERENCES [dbo].[SCM_ProdLineFact] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

