ALTER TABLE [dbo].[ORD_OrderDet]
    ADD CONSTRAINT [FK_ORD_ORDE_0_REFERENCE_SCM_PICK] FOREIGN KEY ([PickStrategy]) REFERENCES [dbo].[SCM_PickStrategy] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

