ALTER TABLE [dbo].[ORD_ContOrderDet]
    ADD CONSTRAINT [FK_ORD_CONT_REFERENCE_INV_CONT] FOREIGN KEY ([ContId]) REFERENCES [dbo].[INV_ContainerDet] ([ContId]) ON DELETE NO ACTION ON UPDATE NO ACTION;

