ALTER TABLE [dbo].[ORD_MiscOrderLocationDet]
    ADD CONSTRAINT [FK_ORD_MISC_REFERENCE_ORD_MISC3] FOREIGN KEY ([MiscOrderDetId]) REFERENCES [dbo].[ORD_MiscOrderDet] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

