ALTER TABLE [dbo].[ORD_IpLocationDet_0]
    ADD CONSTRAINT [FK_ORD_IpLocationDet0_ActBill_REFERENCE_BIL_ActBill_Id] FOREIGN KEY ([ActBill]) REFERENCES [dbo].[BIL_ActBill] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

