ALTER TABLE [dbo].[ORD_OrderMstr_2]
    ADD CONSTRAINT [FK_ORD_OrderMstr2_Flow_REFERENCE_SCM_FlowMstr_Code] FOREIGN KEY ([Flow]) REFERENCES [dbo].[SCM_FlowMstr] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

