ALTER TABLE [dbo].[ORD_OrderMstr_5]
    ADD CONSTRAINT [FK_ORD_OrderMstr5_Shift_REFERENCE_PRD_ShiftMstr_Code] FOREIGN KEY ([Shift]) REFERENCES [dbo].[PRD_ShiftMstr] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

