ALTER TABLE [dbo].[ORD_OrderBackflushDet]
    ADD CONSTRAINT [FK_ORD_ORDE_REFERENCE_MD_LOCAT4] FOREIGN KEY ([LocFrom]) REFERENCES [dbo].[MD_Location] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

