ALTER TABLE [dbo].[ORD_PickListDet]
    ADD CONSTRAINT [FK_ORD_PICK_REFERENCE_SCM_PICK] FOREIGN KEY ([PickStrategy]) REFERENCES [dbo].[SCM_PickStrategy] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

