ALTER TABLE [dbo].[ORD_RecMstr_7]
    ADD CONSTRAINT [FK_ORD_RecMstr7_ShipFrom_REFERENCE_MD_Address_Code] FOREIGN KEY ([ShipFrom]) REFERENCES [dbo].[MD_Address] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

