ALTER TABLE [dbo].[ORD_MiscOrderLocationDet]
    ADD CONSTRAINT [FK_ORD_MISC_REFERENCE_BIL_ACTB] FOREIGN KEY ([ActBill]) REFERENCES [dbo].[BIL_ActBill] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

