ALTER TABLE [dbo].[ORD_IpLocationDet_5]
    ADD CONSTRAINT [FK_ORD_IpLocationDet5_HuId_REFERENCE_INV_Hu_HuId] FOREIGN KEY ([HuId]) REFERENCES [dbo].[INV_Hu] ([HuId]) ON DELETE NO ACTION ON UPDATE NO ACTION;

