ALTER TABLE [dbo].[ORD_OrderBackflushDet]
    ADD CONSTRAINT [FK_ORD_ORDE_REFERENCE_MD_PARTY5] FOREIGN KEY ([ManufactureParty]) REFERENCES [dbo].[MD_Party] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

