ALTER TABLE [dbo].[ORD_IpMstr_0]
    ADD CONSTRAINT [FK_ORD_IpMstr0_ShipTo_REFERENCE_MD_Address_Code] FOREIGN KEY ([ShipTo]) REFERENCES [dbo].[MD_Address] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

