ALTER TABLE [dbo].[ORD_MiscOrderLocationDet]
    ADD CONSTRAINT [FK_ORD_MISC_REFERENCE_MD_SUPPL] FOREIGN KEY ([CSSupplier]) REFERENCES [dbo].[MD_Supplier] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

