ALTER TABLE [dbo].[ORD_OrderMstr]
    ADD CONSTRAINT [FK_ORD_ORDE_REFERENCE_SCM_PICK2] FOREIGN KEY ([PickStrategy]) REFERENCES [dbo].[SCM_PickStrategy] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

