ALTER TABLE [dbo].[ORD_PickListDet]
    ADD CONSTRAINT [FK_ORD_PICK_REFERENCE_MD_PARTY] FOREIGN KEY ([ManufactureParty]) REFERENCES [dbo].[MD_Party] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

