ALTER TABLE [dbo].[ORD_IpMstr_3]
    ADD CONSTRAINT [FK_ORD_IpMstr3_ShipFrom_REFERENCE_MD_Address_Code] FOREIGN KEY ([ShipFrom]) REFERENCES [dbo].[MD_Address] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

