ALTER TABLE [dbo].[ORD_OrderDet]
    ADD CONSTRAINT [FK_ORD_ORDE_0_REFERENCE_MD_PARTY4] FOREIGN KEY ([ManufactureParty]) REFERENCES [dbo].[MD_Party] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

