ALTER TABLE [dbo].[ORD_OrderBackflushDet]
    ADD CONSTRAINT [FK_ORD_ORDE_REFERENCE_SCM_FLOW4] FOREIGN KEY ([ProdLine]) REFERENCES [dbo].[SCM_FlowMstr] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

