ALTER TABLE [dbo].[ORD_OrderDet_7]
    ADD CONSTRAINT [FK_ORD_OrderDet7_Bom_REFERENCE_PRD_BomMstr_Code] FOREIGN KEY ([Bom]) REFERENCES [dbo].[PRD_BomMstr] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

