ALTER TABLE [dbo].[ORD_OrderDet]
    ADD CONSTRAINT [FK_ORD_ORDE_0_REFERENCE_BIL_PRIC] FOREIGN KEY ([PriceList]) REFERENCES [dbo].[BIL_PriceListMstr] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

