ALTER TABLE [dbo].[ORD_OrderBackflushDet]
    ADD CONSTRAINT [FK_ORD_ORDE_REFERENCE_BIL_PLAN] FOREIGN KEY ([PlanBill]) REFERENCES [dbo].[BIL_PlanBill] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

