ALTER TABLE [dbo].[ORD_OrderBindingDet]
    ADD CONSTRAINT [FK_ORD_ORDE_REFERENCE_ORD_ORDE14] FOREIGN KEY ([OrderBomDetId]) REFERENCES [dbo].[ORD_OrderBomDet] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

