ALTER TABLE [dbo].[ORD_MiscOrderLocationDet]
    ADD CONSTRAINT [FK_ORD_MISC_REFERENCE_BIL_PLAN] FOREIGN KEY ([PlanBill]) REFERENCES [dbo].[BIL_PlanBill] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

