ALTER TABLE [dbo].[ORD_PickListResult]
    ADD CONSTRAINT [FK_ORD_PICK_REFERENCE_ORD_PICK3] FOREIGN KEY ([PLDetId]) REFERENCES [dbo].[ORD_PickListDet] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

