ALTER TABLE [dbo].[ORD_OrderBindingDet]
    ADD CONSTRAINT [FK_ORD_ORDE_REFERENCE_ORD_ORDE10] FOREIGN KEY ([OrderBindingId]) REFERENCES [dbo].[ORD_OrderBinding] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

