ALTER TABLE [dbo].[ORD_ContOrderDet]
    ADD CONSTRAINT [FK_ORD_CONT_REFERENCE_ORD_CONT] FOREIGN KEY ([OrderNo]) REFERENCES [dbo].[ORD_ContOrderMstr] ([OrderNo]) ON DELETE NO ACTION ON UPDATE NO ACTION;

