ALTER TABLE [dbo].[ORD_IpDet_3]
    ADD CONSTRAINT [FK_ORD_IpDet3_Container_REFERENCE_MD_Container_Code] FOREIGN KEY ([Container]) REFERENCES [dbo].[MD_Container] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

