ALTER TABLE [dbo].[ORD_OrderDet_3]
    ADD CONSTRAINT [FK_ORD_OrderDet3_LocFrom_REFERENCE_MD_Location_Code] FOREIGN KEY ([LocFrom]) REFERENCES [dbo].[MD_Location] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

