ALTER TABLE [dbo].[PRD_PlanBackflush]
    ADD CONSTRAINT [FK_PRD_PLAN_REFERENCE_ORD_ORDE] FOREIGN KEY ([OrderBomDetId]) REFERENCES [dbo].[ORD_OrderBomDet] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

