ALTER TABLE [dbo].[PRD_ProdLineWorkCenter]
    ADD CONSTRAINT [FK_PRD_PROD_REFERENCE_SCM_FLOW2] FOREIGN KEY ([Flow]) REFERENCES [dbo].[SCM_FlowMstr] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

