ALTER TABLE [dbo].[PRD_ProdLineLocationDet]
    ADD CONSTRAINT [FK_PRD_PROD_REFERENCE_BIL_PLAN] FOREIGN KEY ([PlanBill]) REFERENCES [dbo].[BIL_PlanBill] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

