ALTER TABLE [dbo].[PRD_PlanBackflush]
    ADD CONSTRAINT [FK_PRD_PLAN_REFERENCE_SCM_PROD] FOREIGN KEY ([ProdLineFact]) REFERENCES [dbo].[SCM_ProdLineFact] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

