ALTER TABLE [dbo].[PRD_ProdLineLocationDet]
    ADD CONSTRAINT [FK_PRD_PROD_REFERENCE_SCM_PROD] FOREIGN KEY ([ProdLineFact]) REFERENCES [dbo].[SCM_ProdLineFact] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

