ALTER TABLE [dbo].[PRD_StandardWorkingCalendar]
    ADD CONSTRAINT [FK_PRD_STAN_REFERENCE_PRD_SHIF] FOREIGN KEY ([Shift]) REFERENCES [dbo].[PRD_ShiftMstr] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

