ALTER TABLE [dbo].[PRD_WorkingCalendar]
    ADD CONSTRAINT [FK_PRD_WORKingCalendar_REFERENCE_PRD_SHIFMSTR_CODE] FOREIGN KEY ([Shift]) REFERENCES [dbo].[PRD_ShiftMstr] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

