ALTER TABLE [dbo].[PRD_ProdLineLocationDet]
    ADD CONSTRAINT [FK_PRD_PROD_REFERENCE_MD_LOCAT] FOREIGN KEY ([LocFrom]) REFERENCES [dbo].[MD_Location] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

