ALTER TABLE [dbo].[PRD_ProdLineLocationDet]
    ADD CONSTRAINT [FK_PRD_PROD_REFERENCE_SCM_FLOW] FOREIGN KEY ([ProdLine]) REFERENCES [dbo].[SCM_FlowMstr] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

