ALTER TABLE [dbo].[PRD_ProdLineWorkCenter]
    ADD CONSTRAINT [FK_PRD_PROD_REFERENCE_MD_WORKC] FOREIGN KEY ([WorkCenter]) REFERENCES [dbo].[MD_WorkCenter] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

