ALTER TABLE [dbo].[PRD_WorkingShift]
    ADD CONSTRAINT [FK_PRD_WORK_REFERENCE_MD_WORKI] FOREIGN KEY ([WorkingCalendar]) REFERENCES [dbo].[MD_WorkingCalendar] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

