ALTER TABLE [dbo].[PRD_StandardWorkingCalendar]
    ADD CONSTRAINT [FK_PRD_STAN_REFERENCE_MD_REGIO] FOREIGN KEY ([Region]) REFERENCES [dbo].[MD_Region] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

