ALTER TABLE [dbo].[PRD_MultiSupplyItem]
    ADD CONSTRAINT [FK_PRD_MULT_REFERENCE_PRD_MULT2] FOREIGN KEY ([GroupNo]) REFERENCES [dbo].[PRD_MultiSupplyGroup] ([GroupNo]) ON DELETE NO ACTION ON UPDATE NO ACTION;

