ALTER TABLE [dbo].[PRD_MultiSupplySupplier]
    ADD CONSTRAINT [FK_PRD_MULT_REFERENCE_MD_SUPPL2] FOREIGN KEY ([Supplier]) REFERENCES [dbo].[MD_Supplier] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

