ALTER TABLE [dbo].[PRD_MultiSupplySupplier]
    ADD CONSTRAINT [FK_PRD_MULT_REFERENCE_PRD_MULT] FOREIGN KEY ([GroupNo]) REFERENCES [dbo].[PRD_MultiSupplyGroup] ([GroupNo]) ON DELETE NO ACTION ON UPDATE NO ACTION;

