ALTER TABLE [dbo].[SCM_FlowMstr]
    ADD CONSTRAINT [FK_SCM_FLOW_REFERENCE_PRD_ROUT3] FOREIGN KEY ([ReturnRouting]) REFERENCES [dbo].[PRD_RoutingMstr] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

