ALTER TABLE [dbo].[SCM_FlowMstr]
    ADD CONSTRAINT [FK_SCM_FLOW_REFERENCE_BIL_PRIC2] FOREIGN KEY ([PriceList]) REFERENCES [dbo].[BIL_PriceListMstr] ([Code]) ON DELETE NO ACTION ON UPDATE NO ACTION;

