ALTER TABLE [dbo].[FIS_InboundCtrl]
    ADD CONSTRAINT [PK__FIS_Inbo__3214EC07503D80CA] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

