ALTER TABLE [dbo].[INV_HuMapping]
    ADD CONSTRAINT [PK__INV_HuMa__3214EC071645E95F] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

