ALTER TABLE [dbo].[BIL_BillTrans]
    ADD CONSTRAINT [PK_BIL_BILLTRANS] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

