ALTER TABLE [dbo].[CUST_VanJob]
    ADD CONSTRAINT [PK_CUST_VanJob] PRIMARY KEY CLUSTERED ([JobId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

