ALTER TABLE [dbo].[CUST_RoutingPositionMap]
    ADD CONSTRAINT [PK_CUST_ROUTINGPOSITIONMAP] PRIMARY KEY CLUSTERED ([SAPPosition] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

