ALTER TABLE [dbo].[CUST_OpReport]
    ADD CONSTRAINT [PK_CUST_OPREPORT] PRIMARY KEY CLUSTERED ([OrderNo] ASC, [WorkCenter] ASC, [Op] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

