ALTER TABLE [dbo].[CUST_ProductLineMap]
    ADD CONSTRAINT [PK_CUST_PRODUCTLINEMAP] PRIMARY KEY CLUSTERED ([SAPProdLine] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

