ALTER TABLE [dbo].[CUST_ProdLineLocationMap]
    ADD CONSTRAINT [PK_CUST_ProdLineLocationMap] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

