ALTER TABLE [dbo].[CUST_ItemAverage]
    ADD CONSTRAINT [PK_CUST_ITEMAVERAGE] PRIMARY KEY CLUSTERED ([Item] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

