ALTER TABLE [dbo].[FIS_CreateOrderDAT]
    ADD CONSTRAINT [PK_FIS_CreateOrderDAT] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

