ALTER TABLE [dbo].[INV_LocTrans_13]
    ADD CONSTRAINT [PK_INV_LOCTRANS_0_13] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

