ALTER TABLE [dbo].[INP_ConcessionMstr]
    ADD CONSTRAINT [PK_INP_CONCESSIONMSTR] PRIMARY KEY CLUSTERED ([CCSNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

