ALTER TABLE [dbo].[ISS_IssueLog]
    ADD CONSTRAINT [PK_ISS_ISSUELOG] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

