ALTER TABLE [dbo].[INV_ContainerDet]
    ADD CONSTRAINT [PK_INV_CONTAINERDET] PRIMARY KEY CLUSTERED ([ContId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

