ALTER TABLE [dbo].[SAP_InvTrans]
    ADD CONSTRAINT [PK_InvTrans] PRIMARY KEY CLUSTERED ([FRBNR] ASC, [SGTXT] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

