ALTER TABLE [dbo].[INV_Hu]
    ADD CONSTRAINT [PK_INV_HU] PRIMARY KEY CLUSTERED ([HuId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

