ALTER TABLE [dbo].[LE_FlowDetSnapShot]
    ADD CONSTRAINT [PK_LE_FlowDetSnapShot_1] PRIMARY KEY CLUSTERED ([Item] ASC, [LocTo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

