ALTER TABLE [dbo].[LE_LocationDetSnapshot]
    ADD CONSTRAINT [PK_LE_LocationDetSnapshot] PRIMARY KEY CLUSTERED ([Item] ASC, [Location] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

