ALTER TABLE [dbo].[LE_FlowMstrSnapShot]
    ADD CONSTRAINT [PK_LE_FlowMstrSnapShot] PRIMARY KEY CLUSTERED ([Flow] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

