ALTER TABLE [dbo].[LE_FlowDetExtraDmdSource]
    ADD CONSTRAINT [PK_LE_FlowDetExtraDmdSource] PRIMARY KEY CLUSTERED ([FlowDetId] ASC, [Location] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

