ALTER TABLE [dbo].[MD_FinanceCalendar]
    ADD CONSTRAINT [PK_MD_FINANCECALENDAR] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

