ALTER TABLE [dbo].[MD_ItemPackage_bak]
    ADD CONSTRAINT [PK_MD_ITEMPACKAG_bakE] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

