ALTER TABLE [dbo].[ORD_RecMstr_7]
    ADD CONSTRAINT [PK_ORD_RecMstr_0_7] PRIMARY KEY CLUSTERED ([RecNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

