ALTER TABLE [dbo].[ORD_RecDet_0]
    ADD CONSTRAINT [PK_ORD_RecDet_0_0] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

