ALTER TABLE [dbo].[ORD_OrderDet_2]
    ADD CONSTRAINT [PK_ORD_OrderDet_0_2] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

