ALTER TABLE [dbo].[ORD_PickTask]
    ADD CONSTRAINT [PK_ORD_PickTask] PRIMARY KEY CLUSTERED ([PickId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

