ALTER TABLE [dbo].[ORD_IpMstr_1]
    ADD CONSTRAINT [PK_ORD_IpMstr_0_1] PRIMARY KEY CLUSTERED ([IpNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

