ALTER TABLE [dbo].[ORD_ContOrderDet]
    ADD CONSTRAINT [PK_ORD_CONTORDERDET] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

