ALTER TABLE [dbo].[ORD_SeqMstr]
    ADD CONSTRAINT [PK_ORD_SEQMSTR] PRIMARY KEY CLUSTERED ([SeqNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

