ALTER TABLE [dbo].[ORD_PickResult]
    ADD CONSTRAINT [PK_ORD_PickResult] PRIMARY KEY CLUSTERED ([ResultId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

