ALTER TABLE [dbo].[ORD_ContOrderMstr]
    ADD CONSTRAINT [PK_ORD_CONTORDERMSTR] PRIMARY KEY CLUSTERED ([OrderNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

