ALTER TABLE [dbo].[ORD_OrderMstr_8]
    ADD CONSTRAINT [PK_ORD_OrderMstr_8] PRIMARY KEY CLUSTERED ([OrderNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

