ALTER TABLE [dbo].[ORD_RecLocationDet_5]
    ADD CONSTRAINT [PK_ORD_RecLocationDet_0_5] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

