ALTER TABLE [dbo].[ORD_PickListMstr]
    ADD CONSTRAINT [PK_ORD_PICKLISTMSTR] PRIMARY KEY CLUSTERED ([PLNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

