ALTER TABLE [dbo].[ORD_ShipList]
    ADD CONSTRAINT [PK_ORD_ShipList] PRIMARY KEY CLUSTERED ([ShipNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

