ALTER TABLE [dbo].[ORD_OrderBackflushDet]
    ADD CONSTRAINT [PK_ORD_ORDERBACKFLUSHDET] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

