ALTER TABLE [dbo].[ORD_MiscOrderMstr]
    ADD CONSTRAINT [PK_ORD_MISCORDERMSTR] PRIMARY KEY CLUSTERED ([MiscOrderNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

