ALTER TABLE [dbo].[PRD_MultiSupplyGroup]
    ADD CONSTRAINT [PK_PRD_MULTISUPPLYGROUP] PRIMARY KEY CLUSTERED ([GroupNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

