ALTER TABLE [dbo].[PRD_PlanBackflush]
    ADD CONSTRAINT [PK_PRD_PLANBACKFLUSH] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

