ALTER TABLE [dbo].[PRD_ShiftMstr]
    ADD CONSTRAINT [PK_PRD_SHIFTMSTR] PRIMARY KEY CLUSTERED ([Code] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

