ALTER TABLE [dbo].[SAP_ProdSeqReport]
    ADD CONSTRAINT [PK_SAP_ProdSeqReport] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

