ALTER TABLE [dbo].[SAP_ProdRoutingDet]
    ADD CONSTRAINT [PK_SAP_PRODROUTINGDET] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

