ALTER TABLE [dbo].[SCM_ProdLineFact]
    ADD CONSTRAINT [PK_SCM_PRODLINEFACT] PRIMARY KEY CLUSTERED ([Code] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

