ALTER TABLE [dbo].[SAP_TableIndex]
    ADD CONSTRAINT [PK_TableIndex] PRIMARY KEY CLUSTERED ([TableName] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

