ALTER TABLE [dbo].[CUST_VehicleInFactoryMstr]
    ADD CONSTRAINT [PK_VehicleInFactoryMstr] PRIMARY KEY CLUSTERED ([OrderNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

