CREATE UNIQUE NONCLUSTERED INDEX [Index_1]
    ON [dbo].[MD_UomConv]([Item] ASC, [BaseUom] ASC, [AltUom] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

