CREATE TABLE [dbo].[BIL_BillTrans] (
    [Id]           INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [OrderNo]      VARCHAR (50)    NOT NULL,
    [IpNo]         VARCHAR (50)    NULL,
    [ExtIpNo]      VARCHAR (50)    NULL,
    [RecNo]        VARCHAR (50)    NULL,
    [ExtRecNo]     VARCHAR (50)    NULL,
    [IsIncludeTax] BIT             NOT NULL,
    [Item]         VARCHAR (50)    NOT NULL,
    [ItemDesc]     VARCHAR (100)   NOT NULL,
    [Uom]          VARCHAR (5)     NOT NULL,
    [UC]           DECIMAL (18, 8) NOT NULL,
    [HuId]         VARCHAR (50)    NULL,
    [TransType]    TINYINT         NOT NULL,
    [BillAddr]     VARCHAR (50)    NOT NULL,
    [BillAddrDesc] VARCHAR (256)   NULL,
    [Party]        VARCHAR (50)    NOT NULL,
    [PartyNm]      VARCHAR (100)   NULL,
    [PriceList]    VARCHAR (50)    NULL,
    [Currency]     VARCHAR (50)    NULL,
    [UnitPrice]    DECIMAL (18, 8) NOT NULL,
    [IsProvEst]    BIT             NOT NULL,
    [Tax]          VARCHAR (50)    NULL,
    [BillQty]      DECIMAL (18, 8) NOT NULL,
    [BillAmount]   DECIMAL (18, 8) NOT NULL,
    [UnitQty]      DECIMAL (18, 8) NOT NULL,
    [LocFrom]      VARCHAR (50)    NULL,
    [SettleLoc]    VARCHAR (50)    NULL,
    [EffDate]      DATETIME        NOT NULL,
    [PlanBill]     INT             NULL,
    [ActBill]      INT             NULL,
    [CreateUser]   INT             NOT NULL,
    [CreateUserNm] VARCHAR (100)   NOT NULL,
    [CreateDate]   DATETIME        NOT NULL
);

