CREATE TABLE [dbo].[BIL_BillDet] (
    [Id]               INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [BillNo]           VARCHAR (50)    NOT NULL,
    [ActBill]          INT             NOT NULL,
    [Item]             VARCHAR (50)    NOT NULL,
    [ItemDesc]         VARCHAR (100)   NOT NULL,
    [Uom]              VARCHAR (5)     NOT NULL,
    [UC]               DECIMAL (18, 8) NOT NULL,
    [Qty]              DECIMAL (18, 8) NOT NULL,
    [PriceList]        VARCHAR (50)    NOT NULL,
    [Amount]           DECIMAL (18, 8) NOT NULL,
    [UnitPrice]        DECIMAL (18, 8) NOT NULL,
    [OrderNo]          VARCHAR (50)    NOT NULL,
    [IpNo]             VARCHAR (50)    NULL,
    [ExtIpNo]          VARCHAR (50)    NULL,
    [RecNo]            VARCHAR (50)    NULL,
    [ExtRecNo]         VARCHAR (50)    NULL,
    [CreateUser]       INT             NOT NULL,
    [CreateUserNm]     VARCHAR (100)   NOT NULL,
    [CreateDate]       DATETIME        NOT NULL,
    [LastModifyUser]   INT             NOT NULL,
    [LastModifyUserNm] VARCHAR (100)   NOT NULL,
    [LastModifyDate]   DATETIME        NOT NULL,
    [Version]          INT             NOT NULL
);

