CREATE TABLE [dbo].[CUST_WMSKitOrder] (
    [Id]               INT             IDENTITY (1, 1) NOT NULL,
    [Flow]             VARCHAR (50)    NULL,
    [SapProdLine]      VARCHAR (50)    NULL,
    [SapOrderNo]       VARCHAR (50)    NULL,
    [Van]              VARCHAR (50)    NULL,
    [Item]             VARCHAR (50)    NULL,
    [RefItemCode]      VARCHAR (50)    NULL,
    [ItemDesc]         VARCHAR (100)   NULL,
    [UOM]              VARCHAR (5)     NULL,
    [ManufactureParty] VARCHAR (50)    NULL,
    [OpRef]            VARCHAR (50)    NULL,
    [OrderQty]         DECIMAL (18, 8) NULL,
    [ReserveNo]        VARCHAR (50)    NULL,
    [ReserveLine]      VARCHAR (50)    NULL,
    [ZOPWZ]            VARCHAR (50)    NULL,
    [ZOPID]            VARCHAR (50)    NULL,
    [ZOPDS]            VARCHAR (50)    NULL,
    [AUFNR]            VARCHAR (50)    NULL,
    [ICHARG]           VARCHAR (50)    NULL,
    [BWART]            VARCHAR (50)    NULL,
    [WorkCenter]       VARCHAR (50)    NULL,
    [IsClose]          BIT             NULL,
    [CreateUser]       INT             NULL,
    [CreateUserNm]     VARCHAR (100)   NULL,
    [CreateDate]       DATETIME        NULL,
    [LastModifyUser]   INT             NULL,
    [LastModifyUserNm] VARCHAR (100)   NULL,
    [LastModifyDate]   DATETIME        NULL,
    [Version]          INT             NULL
);

