CREATE TABLE [dbo].[FIS_CreateIpDAT] (
    [Id]             INT           IDENTITY (1, 1) NOT NULL,
    [ASN_NO]         VARCHAR (50)  NOT NULL,
    [ASN_ITEM]       VARCHAR (50)  NOT NULL,
    [WH_CODE]        VARCHAR (50)  NOT NULL,
    [WH_DOCK]        VARCHAR (50)  NULL,
    [WH_LOCATION]    VARCHAR (50)  NULL,
    [ITEM_CODE]      VARCHAR (50)  NOT NULL,
    [SUPPLIER_CODE]  VARCHAR (50)  NOT NULL,
    [QTY]            VARCHAR (50)  NOT NULL,
    [UOM]            VARCHAR (50)  NOT NULL,
    [BASE_UNIT_QTY]  VARCHAR (50)  NOT NULL,
    [BASE_UNIT_UOM]  VARCHAR (50)  NOT NULL,
    [QC_FLAG]        VARCHAR (50)  NOT NULL,
    [DELIVERY_DATE]  VARCHAR (50)  NOT NULL,
    [TIME_WINDOW]    VARCHAR (50)  NULL,
    [PO]             VARCHAR (50)  NOT NULL,
    [FINANCE_FLAG]   VARCHAR (50)  NULL,
    [COMPONENT_FLAG] VARCHAR (50)  NULL,
    [TRACKID]        VARCHAR (50)  NULL,
    [PO_LINE]        VARCHAR (50)  NULL,
    [F80XBJ]         VARCHAR (50)  NULL,
    [F80X_LOCATION]  VARCHAR (50)  NULL,
    [FactoryInfo]    VARCHAR (50)  NULL,
    [ErrorCount]     INT           NULL,
    [IsCreateDat]    BIT           NOT NULL,
    [CreateUserNm]   VARCHAR (100) NULL,
    [TIME_STAMP1]    VARCHAR (50)  NULL,
    [FileName]       VARCHAR (50)  NULL
);

