CREATE TABLE [dbo].[FIS_WMSDatFile] (
    [Id]         INT             IDENTITY (1, 1) NOT NULL,
    [MoveType]   VARCHAR (50)    NOT NULL,
    [BLDAT]      VARCHAR (50)    NULL,
    [BUDAT]      VARCHAR (50)    NULL,
    [PO]         VARCHAR (50)    NULL,
    [POLine]     VARCHAR (50)    NULL,
    [VBELN]      VARCHAR (50)    NULL,
    [POSNR]      VARCHAR (50)    NULL,
    [LIFNR]      VARCHAR (50)    NULL,
    [WERKS]      VARCHAR (50)    NULL,
    [LGORT]      VARCHAR (50)    NULL,
    [SOBKZ]      VARCHAR (50)    NULL,
    [Item]       VARCHAR (50)    NULL,
    [Qty]        DECIMAL (18, 8) NULL,
    [Uom]        VARCHAR (50)    NULL,
    [UMLGO]      VARCHAR (50)    NULL,
    [GRUND]      VARCHAR (50)    NULL,
    [KOSTL]      VARCHAR (50)    NULL,
    [WmsNo]      VARCHAR (50)    NULL,
    [RSNUM]      VARCHAR (50)    NULL,
    [RSPOS]      VARCHAR (50)    NULL,
    [WMSId]      VARCHAR (50)    NULL,
    [WmsLine]    VARCHAR (50)    NULL,
    [OLD]        VARCHAR (50)    NULL,
    [INSMK]      VARCHAR (50)    NULL,
    [XABLN]      VARCHAR (50)    NULL,
    [AUFNR]      VARCHAR (50)    NULL,
    [UMMAT]      VARCHAR (50)    NULL,
    [UMWRK]      VARCHAR (50)    NULL,
    [IsHand]     BIT             NOT NULL,
    [CreateDate] DATETIME        NULL,
    [FileName]   VARCHAR (50)    NULL
);

