CREATE TABLE [dbo].[INP_ConcessionDet] (
    [Id]               INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CCSNo]            VARCHAR (50)    NULL,
    [Seq]              INT             NOT NULL,
    [Item]             VARCHAR (50)    NOT NULL,
    [ItemDesc]         VARCHAR (100)   NOT NULL,
    [RefItemCode]      VARCHAR (50)    NULL,
    [UC]               DECIMAL (18, 8) NOT NULL,
    [Uom]              VARCHAR (5)     NOT NULL,
    [BaseUom]          VARCHAR (5)     NOT NULL,
    [UnitQty]          DECIMAL (18, 8) NOT NULL,
    [HuId]             VARCHAR (50)    NULL,
    [LotNo]            VARCHAR (50)    NULL,
    [LocFrom]          VARCHAR (50)    NOT NULL,
    [LocTo]            VARCHAR (50)    NOT NULL,
    [Qty]              DECIMAL (18, 8) NOT NULL,
    [CreateUser]       INT             NOT NULL,
    [CreateUserNm]     VARCHAR (100)   NOT NULL,
    [CreateDate]       DATETIME        NOT NULL,
    [LastModifyUser]   INT             NOT NULL,
    [LastModifyUserNm] VARCHAR (100)   NOT NULL,
    [LastModifyDate]   DATETIME        NOT NULL,
    [WMSSeq]           VARCHAR (50)    NULL,
    [ManufactureParty] VARCHAR (50)    NULL
);

