CREATE TABLE [dbo].[INP_RejectDet] (
    [Id]               INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [InspResultId]     INT             NOT NULL,
    [InpNo]            VARCHAR (50)    NOT NULL,
    [RejNo]            VARCHAR (50)    NOT NULL,
    [Seq]              INT             NOT NULL,
    [Item]             VARCHAR (50)    NOT NULL,
    [ItemDesc]         VARCHAR (100)   NOT NULL,
    [RefItemCode]      VARCHAR (50)    NULL,
    [UC]               DECIMAL (18, 8) NOT NULL,
    [Uom]              VARCHAR (5)     NOT NULL,
    [BaseUom]          VARCHAR (5)     NOT NULL,
    [UnitQty]          DECIMAL (18, 8) NOT NULL,
    [HuId]             VARCHAR (50)    NULL,
    [LotNo]            VARCHAR (50)    NULL,
    [LocFrom]          VARCHAR (50)    NOT NULL,
    [CurrLoc]          VARCHAR (50)    NOT NULL,
    [HandleQty]        DECIMAL (18, 8) NOT NULL,
    [HandledQty]       DECIMAL (18, 8) NOT NULL,
    [Defect]           VARCHAR (100)   NULL,
    [FailCode]         VARCHAR (50)    NULL,
    [JudgeUser]        INT             NOT NULL,
    [JudgeUserNm]      VARCHAR (100)   NOT NULL,
    [JudgeDate]        DATETIME        NOT NULL,
    [CreateUser]       INT             NOT NULL,
    [CreateUserNm]     VARCHAR (100)   NOT NULL,
    [CreateDate]       DATETIME        NOT NULL,
    [LastModifyUser]   INT             NOT NULL,
    [LastModifyUserNm] VARCHAR (100)   NOT NULL,
    [LastModifyDate]   DATETIME        NOT NULL,
    [Version]          INT             NOT NULL,
    [ManufactureParty] VARCHAR (50)    NULL,
    [IpNo]             VARCHAR (50)    NULL,
    [IpDetSeq]         INT             NULL,
    [RecNo]            VARCHAR (50)    NULL,
    [RecDetSeq]        INT             NULL,
    [WMSNo]            VARCHAR (50)    NULL,
    [WMSSeq]           VARCHAR (50)    NULL
);

