CREATE TABLE [dbo].[INV_ItemExchange] (
    [Id]               INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ItemFrom]         VARCHAR (50)    NOT NULL,
    [ItemTo]           VARCHAR (50)    NOT NULL,
    [RegionFrom]       VARCHAR (50)    NOT NULL,
    [RegionTo]         VARCHAR (50)    NOT NULL,
    [LocationFrom]     VARCHAR (50)    NOT NULL,
    [LocationTo]       VARCHAR (50)    NOT NULL,
    [Qty]              DECIMAL (18, 8) NOT NULL,
    [Uom]              VARCHAR (5)     NOT NULL,
    [BaseUom]          VARCHAR (5)     NOT NULL,
    [UnitQty]          DECIMAL (18, 8) NOT NULL,
    [CreateUser]       INT             NOT NULL,
    [CreateUserNm]     VARCHAR (100)   NOT NULL,
    [CreateDate]       DATETIME        NOT NULL,
    [LastModifyUser]   INT             NOT NULL,
    [LastModifyUserNm] VARCHAR (100)   NOT NULL,
    [LastModifyDate]   DATETIME        NOT NULL,
    [QualityType]      TINYINT         NOT NULL,
    [EffDate]          DATETIME        NOT NULL,
    [IsVoid]           BIT             NOT NULL,
    [WMSNo]            VARCHAR (50)    NULL,
    [WMSSeq]           VARCHAR (50)    NULL
);

