CREATE TABLE [dbo].[INV_StockTakeMstr] (
    [StNo]             VARCHAR (50)  NOT NULL,
    [Type]             TINYINT       NOT NULL,
    [Region]           VARCHAR (50)  NOT NULL,
    [BaseInvDate]      DATETIME      NULL,
    [EffDate]          DATETIME      NULL,
    [Status]           TINYINT       NOT NULL,
    [IsScanHu]         BIT           NOT NULL,
    [CreateUser]       INT           NOT NULL,
    [CreateUserNm]     VARCHAR (100) NOT NULL,
    [CreateDate]       DATETIME      NOT NULL,
    [LastModifyUser]   INT           NOT NULL,
    [LastModifyUserNm] VARCHAR (100) NOT NULL,
    [LastModifyDate]   DATETIME      NOT NULL,
    [ReleaseDate]      DATETIME      NULL,
    [ReleaseUser]      INT           NULL,
    [ReleaseUserNm]    VARCHAR (100) NULL,
    [StartDate]        DATETIME      NULL,
    [StartUser]        INT           NULL,
    [StartUserNm]      VARCHAR (100) NULL,
    [CompleteDate]     DATETIME      NULL,
    [CompleteUser]     INT           NULL,
    [CompleteUserNm]   VARCHAR (100) NULL,
    [CloseDate]        DATETIME      NULL,
    [CloseUser]        INT           NULL,
    [CloseUserNm]      VARCHAR (100) NULL,
    [CancelDate]       DATETIME      NULL,
    [CancelUser]       INT           NULL,
    [CancelUserNm]     VARCHAR (100) NULL,
    [CancelReason]     VARCHAR (256) NULL,
    [Version]          INT           NOT NULL,
    [CostCenter]       VARCHAR (50)  NULL
);

