CREATE TABLE [dbo].[INV_Hu] (
    [HuId]             VARCHAR (50)    NOT NULL,
    [LotNo]            VARCHAR (50)    NOT NULL,
    [Item]             VARCHAR (50)    NOT NULL,
    [ItemDesc]         VARCHAR (100)   NOT NULL,
    [RefItemCode]      VARCHAR (50)    NULL,
    [Uom]              VARCHAR (5)     NOT NULL,
    [BaseUom]          VARCHAR (5)     NOT NULL,
    [UC]               DECIMAL (18, 8) NOT NULL,
    [Qty]              DECIMAL (18, 8) NOT NULL,
    [UnitQty]          DECIMAL (18, 8) NOT NULL,
    [ManufactureDate]  DATETIME        NOT NULL,
    [ManufactureParty] VARCHAR (50)    NOT NULL,
    [RemindExpireDate] DATETIME        NULL,
    [ExpireDate]       DATETIME        NULL,
    [HuTemplate]       VARCHAR (50)    NULL,
    [PrintCount]       TINYINT         NOT NULL,
    [FirstInvDate]     DATETIME        NULL,
    [IsOdd]            BIT             NOT NULL,
    [CreateUser]       INT             NOT NULL,
    [CreateUserNm]     VARCHAR (100)   NOT NULL,
    [CreateDate]       DATETIME        NOT NULL,
    [LastModifyUser]   INT             NOT NULL,
    [LastModifyUserNm] VARCHAR (100)   NOT NULL,
    [LastModifyDate]   DATETIME        NOT NULL,
    [ConcessionCount]  TINYINT         NOT NULL,
    [RecNo]            VARCHAR (50)    NULL,
    [SupplierLotNo]    VARCHAR (50)    NULL,
    [OrderNo]          VARCHAR (50)    NULL,
    [IsChangeUC]       BIT             NULL,
    [UCDesc]           VARCHAR (50)    NULL,
    [LocTo]            VARCHAR (50)    NULL,
    [ContainerDesc]    VARCHAR (50)    NULL,
    [Id]               INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL
);

