CREATE TABLE [dbo].[ISS_IssueDet] (
    [Id]                   INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [IssueCode]            VARCHAR (50)  NOT NULL,
    [IssueTypeToUserDetId] INT           NULL,
    [IssueTypeToRoleDetId] INT           NULL,
    [Seq]                  INT           NOT NULL,
    [IssueLevel]           VARCHAR (50)  NOT NULL,
    [IsSubmit]             BIT           NOT NULL,
    [IsInProcess]          BIT           NOT NULL,
    [IsDefault]            BIT           NOT NULL,
    [IsEmail]              BIT           NOT NULL,
    [IsSMS]                BIT           NOT NULL,
    [Priority]             TINYINT       NOT NULL,
    [UserId]               INT           NOT NULL,
    [Email]                VARCHAR (50)  NULL,
    [EmailStatus]          TINYINT       NOT NULL,
    [EmailCount]           INT           NOT NULL,
    [MobilePhone]          VARCHAR (50)  NULL,
    [SMSStatus]            TINYINT       NOT NULL,
    [SMSCount]             INT           NOT NULL,
    [IsActive]             BIT           NOT NULL,
    [CreateUser]           INT           NOT NULL,
    [CreateUserNm]         VARCHAR (100) NOT NULL,
    [CreateDate]           DATETIME      NOT NULL,
    [LastModifyUser]       INT           NOT NULL,
    [LastModifyUserNm]     VARCHAR (100) NOT NULL,
    [LastModifyDate]       DATETIME      NOT NULL
);

