CREATE TABLE [dbo].[ISS_IssueMstr] (
    [Code]             VARCHAR (50)  NOT NULL,
    [IssueAddr]        VARCHAR (50)  NULL,
    [IssueType]        VARCHAR (50)  NOT NULL,
    [Type]             TINYINT       NOT NULL,
    [IssueNo]          VARCHAR (50)  NULL,
    [IssueSubject]     VARCHAR (50)  NULL,
    [BackYards]        VARCHAR (50)  NULL,
    [Content]          VARCHAR (256) NULL,
    [Solution]         VARCHAR (256) NULL,
    [Status]           TINYINT       NOT NULL,
    [Priority]         TINYINT       NOT NULL,
    [FinishedUser]     VARCHAR (50)  NULL,
    [FinishedDate]     DATETIME      NULL,
    [UserName]         VARCHAR (100) NULL,
    [Email]            VARCHAR (50)  NULL,
    [MPhone]           VARCHAR (50)  NULL,
    [CreateUser]       INT           NOT NULL,
    [CreateUserNm]     VARCHAR (100) NOT NULL,
    [CreateDate]       DATETIME      NOT NULL,
    [LastModifyUser]   INT           NOT NULL,
    [LastModifyUserNm] VARCHAR (100) NOT NULL,
    [LastModifyDate]   DATETIME      NOT NULL,
    [ReleaseDate]      DATETIME      NULL,
    [ReleaseUser]      INT           NULL,
    [ReleaseUserNm]    VARCHAR (100) NULL,
    [StartDate]        DATETIME      NULL,
    [StartUser]        INT           NULL,
    [StartUserNm]      VARCHAR (100) NULL,
    [CloseDate]        DATETIME      NULL,
    [CloseUser]        INT           NULL,
    [CloseUserNm]      VARCHAR (100) NULL,
    [CancelDate]       DATETIME      NULL,
    [CancelUser]       INT           NULL,
    [CancelUserNm]     VARCHAR (100) NULL,
    [CompleteDate]     DATETIME      NULL,
    [CompleteUser]     INT           NULL,
    [CompleteUserNm]   VARCHAR (100) NULL,
    [FailCode]         VARCHAR (50)  NULL,
    [DefectCode]       VARCHAR (50)  NULL
);

