CREATE TABLE [dbo].[ISS_SMSStatus] (
    [Id]               INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Issue]            VARCHAR (50)   NULL,
    [IssueDet]         INT            NULL,
    [IssueLevel]       VARCHAR (50)   NULL,
    [MsgID]            VARCHAR (255)  NULL,
    [SeqID]            INT            NULL,
    [SrcID]            VARCHAR (255)  NULL,
    [DestID]           VARCHAR (255)  NULL,
    [ServiceID]        VARCHAR (255)  NULL,
    [SrcTerminalId]    VARCHAR (255)  NULL,
    [SrcTerminalType]  INT            NULL,
    [MsgFmt]           INT            NULL,
    [MsgLength]        INT            NULL,
    [Status]           VARCHAR (255)  NULL,
    [Content_]         VARCHAR (1000) NULL,
    [DoneDatetime]     DATETIME       NULL,
    [SubmitDatetime]   DATETIME       NULL,
    [EventHandler]     VARCHAR (50)   NULL,
    [CreateUser]       INT            NOT NULL,
    [CreateUserNm]     VARCHAR (100)  NOT NULL,
    [CreateDate]       DATETIME       NOT NULL,
    [LastModifyUser]   INT            NOT NULL,
    [LastModifyUserNm] VARCHAR (100)  NOT NULL,
    [LastModifyDate]   DATETIME       NOT NULL
);

