CREATE TABLE [dbo].[MD_Item] (
    [Code]             VARCHAR (50)    NOT NULL,
    [RefCode]          VARCHAR (50)    NULL,
    [Uom]              VARCHAR (5)     NOT NULL,
    [Desc1]            VARCHAR (100)   NULL,
    [UC]               DECIMAL (18, 8) NOT NULL,
    [ItemCategory]     VARCHAR (50)    NULL,
    [IsActive]         BIT             NOT NULL,
    [IsPurchase]       BIT             NOT NULL,
    [IsSales]          BIT             NOT NULL,
    [IsManufacture]    BIT             NOT NULL,
    [IsSubContract]    BIT             NOT NULL,
    [IsCustomerGoods]  BIT             NOT NULL,
    [IsVirtual]        BIT             NOT NULL,
    [IsKit]            BIT             NOT NULL,
    [IsInvFreeze]      BIT             NOT NULL,
    [Bom]              VARCHAR (50)    NULL,
    [Location]         VARCHAR (50)    NULL,
    [Routing]          VARCHAR (50)    NULL,
    [Warranty]         INT             NOT NULL,
    [WarnLeadTime]     INT             NOT NULL,
    [Container]        VARCHAR (50)    NULL,
    [CreateUser]       INT             NOT NULL,
    [CreateUserNm]     VARCHAR (100)   NOT NULL,
    [CreateDate]       DATETIME        NOT NULL,
    [LastModifyUser]   INT             NOT NULL,
    [LastModifyUserNm] VARCHAR (100)   NOT NULL,
    [LastModifyDate]   DATETIME        NOT NULL,
    [ShortCode]        VARCHAR (10)    NULL,
    [MinUC]            DECIMAL (18, 8) NULL,
    [SpecifiedModel]   VARCHAR (100)   NULL,
    [NotBackFlush]     BIT             NULL,
    [DISPO]            VARCHAR (100)   NULL,
    [PLIFZ]            VARCHAR (100)   NULL
);

