CREATE TABLE [dbo].[ORD_PickTask] (
    [PickId]           VARCHAR (50)    NOT NULL,
    [OrderNo]          VARCHAR (50)    NOT NULL,
    [OrdDetId]         INT             NOT NULL,
    [DemandType]       TINYINT         NOT NULL,
    [IsHold]           BIT             NOT NULL,
    [Flow]             VARCHAR (50)    NULL,
    [FlowDesc]         VARCHAR (100)   NULL,
    [Item]             VARCHAR (50)    NULL,
    [ItemDesc]         VARCHAR (100)   NULL,
    [Uom]              VARCHAR (5)     NULL,
    [BaseUom]          VARCHAR (5)     NULL,
    [PartyFrom]        VARCHAR (50)    NULL,
    [PartyFromName]    VARCHAR (100)   NULL,
    [PartyTo]          VARCHAR (50)    NULL,
    [PartyToName]      VARCHAR (100)   NULL,
    [LocationFrom]     VARCHAR (50)    NULL,
    [LocationFromName] VARCHAR (100)   NULL,
    [LocationTo]       VARCHAR (50)    NULL,
    [LocationToName]   VARCHAR (100)   NULL,
    [WindowTime]       DATETIME        NULL,
    [ReleaseDate]      DATETIME        NULL,
    [Supplier]         VARCHAR (50)    NULL,
    [SupplierName]     VARCHAR (100)   NULL,
    [UnitCount]        DECIMAL (18, 8) NULL,
    [OrderedQty]       DECIMAL (18, 8) NULL,
    [PickedQty]        DECIMAL (18, 8) NULL,
    [Picker]           VARCHAR (50)    NULL,
    [PrintCount]       INT             NOT NULL,
    [Memo]             VARCHAR (256)   NULL,
    [CreateUser]       INT             NOT NULL,
    [CreateUserNm]     VARCHAR (100)   NOT NULL,
    [CreateDate]       DATETIME        NOT NULL,
    [LastModifyUser]   INT             NOT NULL,
    [LastModifyUserNm] VARCHAR (100)   NOT NULL,
    [LastModifyDate]   DATETIME        NOT NULL
);

