CREATE TABLE [dbo].[ORD_OrderBackflushDet] (
    [Id]               INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [OrderNo]          VARCHAR (50)    NULL,
    [OrderDetId]       INT             NULL,
    [OrderDetSeq]      INT             NULL,
    [OrderBomDetId]    INT             NULL,
    [OrderBomDetSeq]   INT             NULL,
    [RecNo]            VARCHAR (50)    NULL,
    [RecDetId]         INT             NULL,
    [RecDetSeq]        INT             NULL,
    [Bom]              VARCHAR (50)    NULL,
    [Item]             VARCHAR (50)    NOT NULL,
    [ItemDesc]         VARCHAR (100)   NOT NULL,
    [RefItemCode]      VARCHAR (50)    NULL,
    [Uom]              VARCHAR (5)     NOT NULL,
    [BaseUom]          VARCHAR (5)     NOT NULL,
    [UnitQty]          DECIMAL (18, 8) NOT NULL,
    [ManufactureParty] VARCHAR (50)    NULL,
    [TraceCode]        VARCHAR (50)    NULL,
    [HuId]             VARCHAR (50)    NULL,
    [LotNo]            VARCHAR (50)    NULL,
    [Op]               INT             NULL,
    [OpRef]            VARCHAR (50)    NULL,
    [BFQty]            DECIMAL (18, 8) NOT NULL,
    [BFRejQty]         DECIMAL (18, 8) NOT NULL,
    [BFScrapQty]       DECIMAL (18, 8) NOT NULL,
    [LocFrom]          VARCHAR (50)    NOT NULL,
    [ProdLine]         VARCHAR (50)    NOT NULL,
    [ProdLineFact]     VARCHAR (50)    NULL,
    [ReserveNo]        VARCHAR (50)    NULL,
    [ReserveLine]      VARCHAR (50)    NULL,
    [AUFNR]            VARCHAR (50)    NULL,
    [PlanBill]         INT             NULL,
    [EffDate]          DATETIME        NOT NULL,
    [CreateUser]       INT             NOT NULL,
    [CreateUserNm]     VARCHAR (100)   NOT NULL,
    [CreateDate]       DATETIME        NOT NULL,
    [ICHARG]           VARCHAR (50)    NULL,
    [BWART]            VARCHAR (50)    NULL,
    [NotReport]        BIT             NOT NULL,
    [FGItem]           VARCHAR (50)    NOT NULL,
    [IsVoid]           BIT             NOT NULL,
    [ProdSeqReportId]  INT             NULL,
    [OrderOpId]        INT             NULL,
    [WorkCenter]       VARCHAR (50)    NULL
);

