CREATE TABLE [dbo].[ORD_SeqMstr] (
    [SeqNo]                VARCHAR (50)  NOT NULL,
    [Flow]                 VARCHAR (50)  NULL,
    [Status]               TINYINT       NOT NULL,
    [OrderType]            TINYINT       NOT NULL,
    [QualityType]          TINYINT       NOT NULL,
    [StartTime]            DATETIME      NOT NULL,
    [WinTime]              DATETIME      NOT NULL,
    [PartyFrom]            VARCHAR (50)  NOT NULL,
    [PartyFromNm]          VARCHAR (50)  NULL,
    [PartyTo]              VARCHAR (50)  NOT NULL,
    [PartyToNm]            VARCHAR (50)  NULL,
    [ShipFrom]             VARCHAR (50)  NULL,
    [ShipFromAddr]         VARCHAR (256) NULL,
    [ShipFromTel]          VARCHAR (50)  NULL,
    [ShipFromCell]         VARCHAR (50)  NULL,
    [ShipFromFax]          VARCHAR (50)  NULL,
    [ShipFromContact]      VARCHAR (50)  NULL,
    [ShipTo]               VARCHAR (50)  NULL,
    [ShipToAddr]           VARCHAR (256) NULL,
    [ShipToTel]            VARCHAR (50)  NULL,
    [ShipToCell]           VARCHAR (50)  NULL,
    [ShipToFax]            VARCHAR (50)  NULL,
    [ShipToContact]        VARCHAR (50)  NULL,
    [LocFrom]              VARCHAR (50)  NULL,
    [LocFromNm]            VARCHAR (50)  NULL,
    [LocTo]                VARCHAR (50)  NOT NULL,
    [LocToNm]              VARCHAR (50)  NULL,
    [Dock]                 VARCHAR (50)  NULL,
    [Container]            VARCHAR (50)  NULL,
    [ContainerDesc]        VARCHAR (50)  NULL,
    [IsAutoReceive]        BIT           NOT NULL,
    [IsPrintAsn]           BIT           NOT NULL,
    [IsPrintRec]           BIT           NOT NULL,
    [IsCheckPartyFromAuth] BIT           NOT NULL,
    [IsCheckPartyToAuth]   BIT           NOT NULL,
    [AsnTemplate]          VARCHAR (100) NULL,
    [RecTemplate]          VARCHAR (100) NULL,
    [CreateUser]           INT           NOT NULL,
    [CreateUserNm]         VARCHAR (100) NOT NULL,
    [CreateDate]           DATETIME      NOT NULL,
    [LastModifyUser]       INT           NOT NULL,
    [LastModifyUserNm]     VARCHAR (100) NOT NULL,
    [LastModifyDate]       DATETIME      NOT NULL,
    [PackUser]             INT           NULL,
    [PackUserNm]           VARCHAR (100) NULL,
    [PackDate]             DATETIME      NULL,
    [ShipUser]             INT           NULL,
    [ShipUserNm]           VARCHAR (100) NULL,
    [ShipDate]             DATETIME      NULL,
    [CancelUser]           INT           NULL,
    [CancelUserNm]         VARCHAR (100) NULL,
    [CancelDate]           DATETIME      NULL,
    [CloseDate]            DATETIME      NULL,
    [CloseUser]            INT           NULL,
    [CloseUserNm]          VARCHAR (100) NULL,
    [Version]              INT           NOT NULL
);

