CREATE TABLE [dbo].[ORD_PickListMstr] (
    [PLNo]                 VARCHAR (50)  NOT NULL,
    [Status]               TINYINT       NOT NULL,
    [OrderType]            TINYINT       NOT NULL,
    [QualityType]          TINYINT       NOT NULL,
    [StartTime]            DATETIME      NOT NULL,
    [WinTime]              DATETIME      NOT NULL,
    [PartyFrom]            VARCHAR (50)  NOT NULL,
    [PartyFromNm]          VARCHAR (100) NULL,
    [PartyTo]              VARCHAR (50)  NOT NULL,
    [PartyToNm]            VARCHAR (100) NULL,
    [ShipFrom]             VARCHAR (50)  NULL,
    [ShipFromAddr]         VARCHAR (256) NULL,
    [ShipFromTel]          VARCHAR (50)  NULL,
    [ShipFromCell]         VARCHAR (50)  NULL,
    [ShipFromFax]          VARCHAR (50)  NULL,
    [ShipFromContact]      VARCHAR (50)  NULL,
    [ShipTo]               VARCHAR (50)  NULL,
    [ShipToAddr]           VARCHAR (256) NULL,
    [ShipToTel]            VARCHAR (50)  NULL,
    [ShipToCell]           VARCHAR (50)  NULL,
    [ShipToFax]            VARCHAR (50)  NULL,
    [ShipToContact]        VARCHAR (50)  NULL,
    [Dock]                 VARCHAR (100) NULL,
    [IsAutoReceive]        BIT           NOT NULL,
    [IsPrintAsn]           BIT           NOT NULL,
    [IsPrintRec]           BIT           NOT NULL,
    [IsRecExceed]          BIT           NOT NULL,
    [IsRecFulfillUC]       BIT           NOT NULL,
    [IsRecFifo]            BIT           NOT NULL,
    [IsAsnUniqueRec]       BIT           NOT NULL,
    [IsCheckPartyFromAuth] BIT           NOT NULL,
    [IsCheckPartyToAuth]   BIT           NOT NULL,
    [RecGapTo]             TINYINT       NOT NULL,
    [AsnTemplate]          VARCHAR (100) NULL,
    [RecTemplate]          VARCHAR (100) NULL,
    [HuTemplate]           VARCHAR (100) NULL,
    [EffDate]              DATETIME      NOT NULL,
    [CreateUser]           INT           NOT NULL,
    [CreateUserNm]         VARCHAR (100) NOT NULL,
    [CreateDate]           DATETIME      NOT NULL,
    [LastModifyUser]       INT           NOT NULL,
    [LastModifyUserNm]     VARCHAR (100) NOT NULL,
    [LastModifyDate]       DATETIME      NOT NULL,
    [StartDate]            DATETIME      NULL,
    [StartUser]            INT           NULL,
    [StartUserNm]          VARCHAR (100) NULL,
    [CompleteDate]         DATETIME      NULL,
    [CompleteUser]         INT           NULL,
    [CompleteUserNm]       VARCHAR (100) NULL,
    [CloseDate]            DATETIME      NULL,
    [CloseUser]            INT           NULL,
    [CloseUserNm]          VARCHAR (100) NULL,
    [CancelDate]           DATETIME      NULL,
    [CancelUser]           INT           NULL,
    [CancelUserNm]         VARCHAR (100) NULL,
    [CancelReason]         VARCHAR (256) NULL,
    [Version]              INT           NOT NULL,
    [CreateHuOpt]          TINYINT       NOT NULL,
    [IsRecScanHu]          BIT           NOT NULL,
    [Flow]                 VARCHAR (50)  NULL
);

