CREATE TABLE [dbo].[ORD_OrderBomDet] (
    [Id]               INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [OrderNo]          VARCHAR (50)    NOT NULL,
    [OrderType]        TINYINT         NOT NULL,
    [OrderSubType]     TINYINT         NOT NULL,
    [OrderDetId]       INT             NOT NULL,
    [OrderDetSeq]      INT             NOT NULL,
    [Seq]              INT             NOT NULL,
    [Bom]              VARCHAR (50)    NULL,
    [Item]             VARCHAR (50)    NOT NULL,
    [ItemDesc]         VARCHAR (100)   NOT NULL,
    [RefItemCode]      VARCHAR (50)    NULL,
    [Uom]              VARCHAR (5)     NOT NULL,
    [BaseUom]          VARCHAR (5)     NOT NULL,
    [ManufactureParty] VARCHAR (50)    NULL,
    [Op]               INT             NOT NULL,
    [OpRef]            VARCHAR (50)    NOT NULL,
    [OrderQty]         DECIMAL (18, 8) NOT NULL,
    [BFQty]            DECIMAL (18, 8) NOT NULL,
    [BFRejQty]         DECIMAL (18, 8) NOT NULL,
    [BFScrapQty]       DECIMAL (18, 8) NOT NULL,
    [UnitQty]          DECIMAL (18, 8) NOT NULL,
    [BomUnitQty]       DECIMAL (18, 8) NOT NULL,
    [Location]         VARCHAR (50)    NULL,
    [IsPrint]          BIT             NOT NULL,
    [BackFlushMethod]  TINYINT         NOT NULL,
    [FeedMethod]       TINYINT         NOT NULL,
    [IsAutoFeed]       BIT             NOT NULL,
    [IsScanHu]         BIT             NOT NULL,
    [EstConsumeTime]   DATETIME        NOT NULL,
    [ReserveNo]        VARCHAR (50)    NULL,
    [ReserveLine]      VARCHAR (50)    NULL,
    [ZOPWZ]            VARCHAR (50)    NULL,
    [ZOPID]            VARCHAR (50)    NULL,
    [ZOPDS]            VARCHAR (50)    NULL,
    [AUFNR]            VARCHAR (50)    NULL,
    [CreateUser]       INT             NOT NULL,
    [CreateUserNm]     VARCHAR (100)   NOT NULL,
    [CreateDate]       DATETIME        NOT NULL,
    [LastModifyUser]   INT             NOT NULL,
    [LastModifyUserNm] VARCHAR (100)   NOT NULL,
    [LastModifyDate]   DATETIME        NOT NULL,
    [Version]          INT             NOT NULL,
    [ICHARG]           VARCHAR (50)    NULL,
    [BWART]            VARCHAR (50)    NULL,
    [AssProdLine]      VARCHAR (50)    NULL,
    [IsCreateOrder]    BIT             NULL,
    [DISPO]            VARCHAR (50)    NULL,
    [BESKZ]            VARCHAR (100)   NULL,
    [SOBSL]            VARCHAR (100)   NULL,
    [JointOp]          INT             NULL,
    [WorkCenter]       VARCHAR (50)    NULL
);

