CREATE TABLE [dbo].[ORD_PickListDet] (
    [Id]               INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [PLNo]             VARCHAR (50)    NOT NULL,
    [OrderNo]          VARCHAR (50)    NOT NULL,
    [OrderType]        TINYINT         NOT NULL,
    [OrderSubType]     TINYINT         NOT NULL,
    [OrderDetId]       INT             NOT NULL,
    [OrderDetSeq]      INT             NULL,
    [Seq]              INT             NOT NULL,
    [Item]             VARCHAR (50)    NOT NULL,
    [ItemDesc]         VARCHAR (100)   NOT NULL,
    [RefItemCode]      VARCHAR (50)    NULL,
    [Uom]              VARCHAR (5)     NOT NULL,
    [BaseUom]          VARCHAR (5)     NOT NULL,
    [UnitQty]          DECIMAL (18, 8) NOT NULL,
    [UC]               DECIMAL (18, 8) NOT NULL,
    [QualityType]      TINYINT         NOT NULL,
    [ManufactureParty] VARCHAR (50)    NULL,
    [LocFrom]          VARCHAR (50)    NULL,
    [LocFromNm]        VARCHAR (100)   NULL,
    [Area]             VARCHAR (50)    NULL,
    [Bin]              VARCHAR (50)    NULL,
    [LocTo]            VARCHAR (50)    NULL,
    [LocToNm]          VARCHAR (100)   NULL,
    [Qty]              DECIMAL (18, 8) NOT NULL,
    [PickedQty]        DECIMAL (18, 8) NOT NULL,
    [HuId]             VARCHAR (50)    NULL,
    [LotNo]            VARCHAR (50)    NULL,
    [IsInspect]        BIT             NOT NULL,
    [Memo]             VARCHAR (256)   NULL,
    [PickStrategy]     VARCHAR (50)    NULL,
    [IsClose]          BIT             NOT NULL,
    [IsOdd]            BIT             NOT NULL,
    [IsDevan]          BIT             NOT NULL,
    [IsInventory]      BIT             NOT NULL,
    [CreateUser]       INT             NOT NULL,
    [CreateUserNm]     VARCHAR (100)   NOT NULL,
    [CreateDate]       DATETIME        NOT NULL,
    [LastModifyUser]   INT             NOT NULL,
    [LastModifyUserNm] VARCHAR (100)   NOT NULL,
    [LastModifyDate]   DATETIME        NOT NULL,
    [Version]          INT             NOT NULL,
    [StartTime]        DATETIME        NULL,
    [WindowTime]       DATETIME        NULL
);

