CREATE TABLE [dbo].[ORD_OrderDet_5] (
    [Id]               INT             NOT NULL,
    [OrderNo]          VARCHAR (50)    NOT NULL,
    [OrderType]        TINYINT         NOT NULL,
    [OrderSubType]     TINYINT         NOT NULL,
    [Seq]              INT             NOT NULL,
    [ExtNo]            VARCHAR (50)    NULL,
    [ExtSeq]           VARCHAR (50)    NULL,
    [StartDate]        DATETIME        NULL,
    [EndDate]          DATETIME        NULL,
    [ScheduleType]     TINYINT         NOT NULL,
    [Item]             VARCHAR (50)    NOT NULL,
    [ItemDesc]         VARCHAR (100)   NOT NULL,
    [RefItemCode]      VARCHAR (50)    NULL,
    [Uom]              VARCHAR (5)     NOT NULL,
    [BaseUom]          VARCHAR (5)     NOT NULL,
    [UC]               DECIMAL (18, 8) NOT NULL,
    [UCDesc]           VARCHAR (50)    NULL,
    [MinUC]            DECIMAL (18, 8) NOT NULL,
    [Container]        VARCHAR (50)    NULL,
    [ContainerDesc]    VARCHAR (50)    NULL,
    [QualityType]      TINYINT         NOT NULL,
    [ManufactureParty] VARCHAR (50)    NULL,
    [ReqQty]           DECIMAL (18, 8) NOT NULL,
    [OrderQty]         DECIMAL (18, 8) NOT NULL,
    [ShipQty]          DECIMAL (18, 8) NOT NULL,
    [RecQty]           DECIMAL (18, 8) NOT NULL,
    [RejQty]           DECIMAL (18, 8) NOT NULL,
    [ScrapQty]         DECIMAL (18, 8) NOT NULL,
    [PickQty]          DECIMAL (18, 8) NOT NULL,
    [UnitQty]          DECIMAL (18, 8) NOT NULL,
    [RecLotSize]       DECIMAL (18, 8) NULL,
    [LocFrom]          VARCHAR (50)    NULL,
    [LocFromNm]        VARCHAR (100)   NULL,
    [LocTo]            VARCHAR (50)    NULL,
    [LocToNm]          VARCHAR (100)   NULL,
    [IsInspect]        BIT             NOT NULL,
    [BillAddr]         VARCHAR (50)    NULL,
    [BillAddrDesc]     VARCHAR (256)   NULL,
    [PriceList]        VARCHAR (50)    NULL,
    [UnitPrice]        DECIMAL (18, 8) NULL,
    [IsProvEst]        BIT             NOT NULL,
    [Tax]              VARCHAR (50)    NULL,
    [IsIncludeTax]     BIT             NOT NULL,
    [Currency]         VARCHAR (50)    NULL,
    [Bom]              VARCHAR (50)    NULL,
    [Routing]          VARCHAR (50)    NULL,
    [BillTerm]         TINYINT         NULL,
    [PickStrategy]     VARCHAR (50)    NULL,
    [ExtraDmdSource]   VARCHAR (256)   NULL,
    [IsScanHu]         BIT             NOT NULL,
    [ReserveNo]        VARCHAR (50)    NULL,
    [ReserveLine]      VARCHAR (50)    NULL,
    [ZOPWZ]            VARCHAR (50)    NULL,
    [ZOPID]            VARCHAR (50)    NULL,
    [ZOPDS]            VARCHAR (50)    NULL,
    [CreateUser]       INT             NOT NULL,
    [CreateUserNm]     VARCHAR (100)   NOT NULL,
    [CreateDate]       DATETIME        NOT NULL,
    [LastModifyUser]   INT             NOT NULL,
    [LastModifyUserNm] VARCHAR (100)   NOT NULL,
    [LastModifyDate]   DATETIME        NOT NULL,
    [Version]          INT             NOT NULL,
    [BinTo]            VARCHAR (50)    NULL,
    [WMSSeq]           VARCHAR (50)    NULL,
    [IsChangeUC]       BIT             NOT NULL,
    [AUFNR]            VARCHAR (50)    NULL,
    [ICHARG]           VARCHAR (50)    NULL,
    [BWART]            VARCHAR (50)    NULL,
    [IsCreatePickList] BIT             NULL
);

