CREATE TABLE [dbo].[ORD_SeqDet] (
    [Id]               INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SeqNo]            VARCHAR (50)    NOT NULL,
    [OrderNo]          VARCHAR (50)    NOT NULL,
    [TraceCode]        VARCHAR (50)    NULL,
    [OrderDetId]       INT             NOT NULL,
    [OrderDetSeq]      INT             NOT NULL,
    [Seq]              BIGINT          NOT NULL,
    [Item]             VARCHAR (50)    NOT NULL,
    [ItemDesc]         VARCHAR (100)   NOT NULL,
    [RefItemCode]      VARCHAR (50)    NULL,
    [Uom]              VARCHAR (5)     NOT NULL,
    [UnitQty]          DECIMAL (18, 8) NOT NULL,
    [BaseUom]          VARCHAR (5)     NOT NULL,
    [UC]               DECIMAL (18, 8) NOT NULL,
    [QualityType]      TINYINT         NOT NULL,
    [ManufactureParty] VARCHAR (50)    NULL,
    [Qty]              DECIMAL (18, 8) NOT NULL,
    [IsClose]          BIT             NOT NULL,
    [HuId]             VARCHAR (50)    NULL,
    [LotNo]            VARCHAR (50)    NULL,
    [CreateUser]       INT             NOT NULL,
    [CreateUserNm]     VARCHAR (100)   NOT NULL,
    [CreateDate]       DATETIME        NOT NULL,
    [LastModifyUser]   INT             NOT NULL,
    [LastModifyUserNm] VARCHAR (100)   NOT NULL,
    [LastModifyDate]   DATETIME        NOT NULL,
    [Version]          INT             NOT NULL,
    [StartTime]        DATETIME        NULL,
    [WindowTime]       DATETIME        NULL
);

