CREATE TABLE [dbo].[ORD_RecMstr_5] (
    [RecNo]                VARCHAR (50)  NOT NULL,
    [ExtRecNo]             VARCHAR (50)  NULL,
    [IpNo]                 VARCHAR (50)  NULL,
    [SeqNo]                VARCHAR (50)  NULL,
    [Status]               TINYINT       NOT NULL,
    [Type]                 TINYINT       NOT NULL,
    [OrderType]            TINYINT       NOT NULL,
    [OrderSubType]         TINYINT       NOT NULL,
    [QualityType]          TINYINT       NOT NULL,
    [PartyFrom]            VARCHAR (50)  NOT NULL,
    [PartyFromNm]          VARCHAR (100) NULL,
    [PartyTo]              VARCHAR (50)  NOT NULL,
    [PartyToNm]            VARCHAR (100) NULL,
    [ShipFrom]             VARCHAR (50)  NULL,
    [ShipFromAddr]         VARCHAR (256) NULL,
    [ShipFromTel]          VARCHAR (50)  NULL,
    [ShipFromCell]         VARCHAR (50)  NULL,
    [ShipFromFax]          VARCHAR (50)  NULL,
    [ShipFromContact]      VARCHAR (50)  NULL,
    [ShipTo]               VARCHAR (50)  NULL,
    [ShipToAddr]           VARCHAR (256) NULL,
    [ShipToTel]            VARCHAR (50)  NULL,
    [ShipToCell]           VARCHAR (50)  NULL,
    [ShipToFax]            VARCHAR (50)  NULL,
    [ShipToContact]        VARCHAR (50)  NULL,
    [Dock]                 VARCHAR (100) NULL,
    [EffDate]              DATETIME      NOT NULL,
    [IsPrintRec]           BIT           NOT NULL,
    [IsRecPrinted]         BIT           NOT NULL,
    [IsCheckPartyFromAuth] BIT           NOT NULL,
    [IsCheckPartyToAuth]   BIT           NOT NULL,
    [RecTemplate]          VARCHAR (100) NULL,
    [CreateUser]           INT           NOT NULL,
    [CreateUserNm]         VARCHAR (100) NOT NULL,
    [CreateDate]           DATETIME      NOT NULL,
    [LastModifyUser]       INT           NOT NULL,
    [LastModifyUserNm]     VARCHAR (100) NOT NULL,
    [LastModifyDate]       DATETIME      NOT NULL,
    [Version]              INT           NOT NULL,
    [WMSNo]                VARCHAR (50)  NULL,
    [CreateHuOpt]          TINYINT       NOT NULL,
    [IsRecScanHu]          BIT           NOT NULL,
    [Flow]                 VARCHAR (50)  NULL,
    [CancelReason]         VARCHAR (256) NULL
);

