CREATE TABLE [dbo].[ORD_MiscOrderMstr] (
    [MiscOrderNo]      VARCHAR (50)  NOT NULL,
    [Type]             TINYINT       NOT NULL,
    [Status]           TINYINT       NOT NULL,
    [IsScanHu]         BIT           NOT NULL,
    [MoveType]         VARCHAR (5)   NOT NULL,
    [CancelMoveType]   VARCHAR (5)   NOT NULL,
    [QualityType]      TINYINT       NOT NULL,
    [Region]           VARCHAR (50)  NOT NULL,
    [Location]         VARCHAR (50)  NOT NULL,
    [RecLoc]           VARCHAR (50)  NULL,
    [Note]             VARCHAR (256) NULL,
    [CostCenter]       VARCHAR (50)  NULL,
    [Asn]              VARCHAR (50)  NULL,
    [RefNo]            VARCHAR (50)  NULL,
    [DeliverRegion]    VARCHAR (50)  NULL,
    [WBS]              VARCHAR (50)  NULL,
    [EffDate]          DATETIME      NOT NULL,
    [CreateUser]       INT           NOT NULL,
    [CreateUserNm]     VARCHAR (100) NOT NULL,
    [CreateDate]       DATETIME      NOT NULL,
    [LastModifyUser]   INT           NOT NULL,
    [LastModifyUserNm] VARCHAR (100) NOT NULL,
    [LastModifyDate]   DATETIME      NOT NULL,
    [CloseUser]        INT           NULL,
    [CloseUserNm]      VARCHAR (100) NULL,
    [CloseDate]        DATETIME      NULL,
    [CancelUser]       INT           NULL,
    [CancelUserNm]     VARCHAR (100) NULL,
    [CancelDate]       DATETIME      NULL,
    [Version]          INT           NOT NULL,
    [WMSNo]            VARCHAR (50)  NULL,
    [Consignment]      BIT           NULL,
    [ManufactureParty] VARCHAR (50)  NULL
);

