CREATE TABLE [dbo].[PRD_PlanBackflush] (
    [Id]               INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ProdLine]         VARCHAR (50)    NOT NULL,
    [ProdLineFact]     VARCHAR (50)    NULL,
    [OrderNo]          VARCHAR (50)    NOT NULL,
    [OrderType]        TINYINT         NOT NULL,
    [OrderSubType]     TINYINT         NOT NULL,
    [OrderDetSeq]      INT             NOT NULL,
    [OrderDetId]       INT             NOT NULL,
    [OrderBomDetId]    INT             NOT NULL,
    [OrderBomDetSeq]   INT             NOT NULL,
    [RecNo]            VARCHAR (50)    NOT NULL,
    [RecDetId]         INT             NOT NULL,
    [RecDetSeq]        INT             NOT NULL,
    [Bom]              VARCHAR (50)    NULL,
    [Item]             VARCHAR (50)    NOT NULL,
    [ItemDesc]         VARCHAR (100)   NOT NULL,
    [RefItemCode]      VARCHAR (50)    NULL,
    [Uom]              VARCHAR (5)     NOT NULL,
    [BaseUom]          VARCHAR (5)     NOT NULL,
    [UnitQty]          DECIMAL (18, 8) NOT NULL,
    [Qty]              DECIMAL (18, 8) NOT NULL,
    [ManufactureParty] VARCHAR (50)    NULL,
    [IsClose]          BIT             NOT NULL,
    [ReserveNo]        VARCHAR (50)    NULL,
    [ReserveLine]      VARCHAR (50)    NULL,
    [AUFNR]            VARCHAR (50)    NULL,
    [CreateUser]       INT             NOT NULL,
    [CreateUserNm]     VARCHAR (100)   NOT NULL,
    [CreateDate]       DATETIME        NOT NULL,
    [LastModifyUser]   INT             NOT NULL,
    [LastModifyUserNm] VARCHAR (100)   NOT NULL,
    [LastModifyDate]   DATETIME        NOT NULL,
    [Version]          INT             NOT NULL,
    [ICHARG]           VARCHAR (50)    NULL,
    [BWART]            VARCHAR (50)    NULL,
    [FGItem]           VARCHAR (50)    NOT NULL
);

