CREATE TABLE [dbo].[PRD_ProdLineLocationDet] (
    [Id]               INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ProdLine]         VARCHAR (50)    NOT NULL,
    [ProdLineFact]     VARCHAR (50)    NULL,
    [OrderNo]          VARCHAR (50)    NULL,
    [OrderDetId]       INT             NULL,
    [Op]               INT             NULL,
    [OpRef]            VARCHAR (50)    NULL,
    [TraceCode]        VARCHAR (50)    NULL,
    [Item]             VARCHAR (50)    NOT NULL,
    [ItemDesc]         VARCHAR (100)   NULL,
    [RefItemCode]      VARCHAR (50)    NULL,
    [HuId]             VARCHAR (50)    NULL,
    [LotNo]            VARCHAR (50)    NULL,
    [IsCS]             BIT             NOT NULL,
    [PlanBill]         INT             NULL,
    [QualityType]      TINYINT         NOT NULL,
    [Qty]              DECIMAL (18, 8) NOT NULL,
    [BFQty]            DECIMAL (18, 8) NOT NULL,
    [VoidQty]          DECIMAL (18, 8) NOT NULL,
    [IsClose]          BIT             NOT NULL,
    [LocFrom]          VARCHAR (50)    NOT NULL,
    [CreateUser]       INT             NOT NULL,
    [CreateUserNm]     VARCHAR (100)   NOT NULL,
    [CreateDate]       DATETIME        NOT NULL,
    [LastModifyUser]   INT             NOT NULL,
    [LastModifyUserNm] VARCHAR (100)   NOT NULL,
    [LastModifyDate]   DATETIME        NOT NULL,
    [Version]          INT             NOT NULL,
    [NotReport]        BIT             NOT NULL,
    [ReserveNo]        VARCHAR (50)    NULL,
    [ReserveLine]      VARCHAR (50)    NULL,
    [AUFNR]            VARCHAR (50)    NULL,
    [ICHARG]           VARCHAR (50)    NULL,
    [BWART]            VARCHAR (50)    NULL
);

