CREATE TABLE [dbo].[SAP_ProdBomDet] (
    [Id]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [BatchNo]    INT             NOT NULL,
    [CreateDate] DATETIME        DEFAULT (getdate()) NOT NULL,
    [AUFNR]      VARCHAR (50)    NULL,
    [RSNUM]      INT             NULL,
    [RSPOS]      INT             NULL,
    [WERKS]      VARCHAR (50)    NULL,
    [MATERIAL]   VARCHAR (50)    NULL,
    [BISMT]      VARCHAR (50)    NULL,
    [MAKTX]      VARCHAR (100)   NULL,
    [DISPO]      VARCHAR (50)    NULL,
    [BESKZ]      VARCHAR (50)    NULL,
    [SOBSL]      VARCHAR (50)    NULL,
    [MEINS]      VARCHAR (50)    NULL,
    [MDMNG]      DECIMAL (18, 8) NULL,
    [LGORT]      VARCHAR (50)    NULL,
    [BWART]      VARCHAR (50)    NULL,
    [AUFPL]      INT             NULL,
    [PLNFL]      VARCHAR (50)    NULL,
    [VORNR]      VARCHAR (50)    NULL,
    [GW]         VARCHAR (50)    NULL,
    [WZ]         VARCHAR (50)    NULL,
    [ZOPID]      VARCHAR (50)    NULL,
    [ZOPDS]      VARCHAR (50)    NULL,
    [LIFNR]      VARCHAR (50)    NULL,
    [ICHARG]     VARCHAR (50)    NULL
);

