CREATE TABLE [dbo].[SAP_InvTrans] (
    [TCODE]          VARCHAR (20)    NULL,
    [BWART]          VARCHAR (3)     NULL,
    [BLDAT]          CHAR (8)        NULL,
    [BUDAT]          CHAR (8)        NULL,
    [EBELN]          VARCHAR (50)    NULL,
    [EBELP]          VARCHAR (5)     NULL,
    [VBELN]          VARCHAR (10)    NULL,
    [POSNR]          VARCHAR (6)     NULL,
    [LIFNR]          VARCHAR (10)    NULL,
    [WERKS]          VARCHAR (4)     NULL,
    [LGORT]          VARCHAR (4)     NULL,
    [SOBKZ]          VARCHAR (1)     NULL,
    [MATNR]          VARCHAR (18)    NULL,
    [ERFMG]          DECIMAL (18, 2) NULL,
    [ERFME]          VARCHAR (3)     NULL,
    [UMLGO]          VARCHAR (4)     NULL,
    [GRUND]          VARCHAR (4)     NULL,
    [KOSTL]          VARCHAR (10)    NULL,
    [XBLNR]          VARCHAR (50)    NULL,
    [RSNUM]          VARCHAR (10)    NULL,
    [RSPOS]          VARCHAR (4)     NULL,
    [FRBNR]          VARCHAR (50)    NOT NULL,
    [SGTXT]          VARCHAR (50)    NOT NULL,
    [OLD]            VARCHAR (3)     NULL,
    [INSMK]          VARCHAR (1)     NULL,
    [XABLN]          VARCHAR (10)    NULL,
    [AUFNR]          VARCHAR (50)    NULL,
    [UMMAT]          VARCHAR (18)    NULL,
    [UMWRK]          VARCHAR (4)     NULL,
    [POSID]          VARCHAR (24)    NULL,
    [CreateDate]     DATETIME        NOT NULL,
    [LastModifyDate] DATETIME        NOT NULL,
    [Status]         TINYINT         NOT NULL,
    [ErrorCount]     INT             NOT NULL,
    [BatchNo]        INT             NOT NULL,
    [CHARG]          VARCHAR (50)    NULL,
    [KZEAR]          VARCHAR (1)     NULL,
    [ErrorId]        INT             NULL,
    [ErrorMessage]   VARCHAR (256)   NULL,
    [OrderNo]        VARCHAR (50)    NULL,
    [DetailId]       INT             NULL
);

