CREATE TABLE [dbo].[SCM_FlowMstr] (
    [Code]                 VARCHAR (50)  NOT NULL,
    [Desc1]                VARCHAR (100) NOT NULL,
    [IsActive]             BIT           NOT NULL,
    [Type]                 TINYINT       NOT NULL,
    [RefFlow]              VARCHAR (50)  NULL,
    [PartyFrom]            VARCHAR (50)  NOT NULL,
    [PartyTo]              VARCHAR (50)  NOT NULL,
    [ShipFrom]             VARCHAR (50)  NULL,
    [ShipTo]               VARCHAR (50)  NULL,
    [LocFrom]              VARCHAR (50)  NULL,
    [LocTo]                VARCHAR (50)  NULL,
    [BillAddr]             VARCHAR (50)  NULL,
    [PriceList]            VARCHAR (50)  NULL,
    [Routing]              VARCHAR (50)  NULL,
    [ReturnRouting]        VARCHAR (50)  NULL,
    [Dock]                 VARCHAR (100) NULL,
    [IsAutoCreate]         BIT           NOT NULL,
    [IsAutoRelease]        BIT           NOT NULL,
    [IsAutoStart]          BIT           NOT NULL,
    [IsAutoShip]           BIT           NOT NULL,
    [IsAutoReceive]        BIT           NOT NULL,
    [IsAutoBill]           BIT           NOT NULL,
    [IsListDet]            BIT           NOT NULL,
    [IsManualCreateDet]    BIT           NOT NULL,
    [IsListPrice]          BIT           NOT NULL,
    [IsPrintOrder]         BIT           NOT NULL,
    [IsPrintAsn]           BIT           NOT NULL,
    [IsPrintRcpt]          BIT           NOT NULL,
    [IsShipExceed]         BIT           NOT NULL,
    [IsRecExceed]          BIT           NOT NULL,
    [IsOrderFulfillUC]     BIT           NOT NULL,
    [IsShipFulfillUC]      BIT           NOT NULL,
    [IsRecFulfillUC]       BIT           NOT NULL,
    [IsShipScanHu]         BIT           NOT NULL,
    [IsRecScanHu]          BIT           NOT NULL,
    [IsCreatePL]           BIT           NOT NULL,
    [IsInspect]            BIT           NOT NULL,
    [IsShipFifo]           BIT           NOT NULL,
    [IsRejInspect]         BIT           NOT NULL,
    [IsRecFifo]            BIT           NOT NULL,
    [IsShipByOrder]        BIT           NOT NULL,
    [IsAsnUniqueRec]       BIT           NOT NULL,
    [IsMRP]                BIT           NOT NULL,
    [IsCheckPartyFromAuth] BIT           NOT NULL,
    [IsCheckPartyToAuth]   BIT           NOT NULL,
    [RecGapTo]             TINYINT       NOT NULL,
    [RecTemplate]          VARCHAR (100) NULL,
    [OrderTemplate]        VARCHAR (100) NULL,
    [AsnTemplate]          VARCHAR (100) NULL,
    [HuTemplate]           VARCHAR (100) NULL,
    [BillTerm]             TINYINT       NOT NULL,
    [CreateHuOpt]          TINYINT       NOT NULL,
    [MaxOrderCount]        INT           NOT NULL,
    [MRPOpt]               INT           NOT NULL,
    [IsPause]              BIT           NOT NULL,
    [PauseTime]            DATETIME      NULL,
    [FlowStrategy]         TINYINT       NOT NULL,
    [ExtraDmdSource]       VARCHAR (256) NULL,
    [PickStrategy]         VARCHAR (50)  NULL,
    [CreateUser]           INT           NOT NULL,
    [CreateUserNm]         VARCHAR (100) NOT NULL,
    [CreateDate]           DATETIME      NOT NULL,
    [LastModifyUser]       INT           NOT NULL,
    [LastModifyUserNm]     VARCHAR (100) NOT NULL,
    [LastModifyDate]       DATETIME      NOT NULL,
    [DAUAT]                VARCHAR (50)  NULL,
    [LastRefreshDate]      DATETIME      NULL,
    [ProdLineType]         TINYINT       NOT NULL,
    [TaktTime]             INT           NULL,
    [VirtualOpRef]         VARCHAR (50)  NULL,
    [WorkCenter]           VARCHAR (50)  NULL
);

