CREATE TABLE [dbo].[SCM_FlowStrategy] (
    [Flow]             VARCHAR (50)    NOT NULL,
    [Strategy]         TINYINT         NOT NULL,
    [Desc1]            VARCHAR (100)   NULL,
    [LeadTime]         DECIMAL (18, 8) NOT NULL,
    [EmLeadTime]       DECIMAL (18, 8) NOT NULL,
    [TimeUnit]         TINYINT         NOT NULL,
    [WinTime1]         VARCHAR (256)   NULL,
    [WinTime2]         VARCHAR (256)   NULL,
    [WinTime3]         VARCHAR (256)   NULL,
    [WinTime4]         VARCHAR (256)   NULL,
    [WinTime5]         VARCHAR (256)   NULL,
    [WinTime6]         VARCHAR (256)   NULL,
    [WinTime7]         VARCHAR (256)   NULL,
    [WeekInterval]     INT             NOT NULL,
    [NextOrderTime]    DATETIME        NULL,
    [NextWinTime]      DATETIME        NULL,
    [CreateUser]       INT             NOT NULL,
    [CreateUserNm]     VARCHAR (100)   NOT NULL,
    [CreateDate]       DATETIME        NOT NULL,
    [LastModifyUser]   INT             NOT NULL,
    [LastModifyUserNm] VARCHAR (100)   NOT NULL,
    [LastModifyDate]   DATETIME        NOT NULL,
    [WinTimeType]      TINYINT         NOT NULL,
    [WinTimeDiff]      DECIMAL (18, 8) NOT NULL,
    [SeqGroup]         VARCHAR (50)    NULL,
    [QiTiaoBian]       VARCHAR (10)    NULL,
    [SupplierGroup]    VARCHAR (50)    NULL,
    [KBCalc]           TINYINT         NULL,
    [SupplierGroupSeq] INT             NULL,
    [NextWinTime2]     DATETIME        NULL,
    [PreOrderTime]     DATETIME        NULL,
    [PreWinTime]       DATETIME        NULL,
    [PreWinTime2]      DATETIME        NULL,
    [WaitTime]         DECIMAL (18, 8) NULL,
    [WaitBatch]        INT             NULL,
    [WinTimeInterval]  DECIMAL (18, 8) NULL
);

