CREATE TABLE [dbo].[SCM_FlowDet] (
    [Id]               INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Flow]             VARCHAR (50)    NOT NULL,
    [Seq]              INT             NOT NULL,
    [Item]             VARCHAR (50)    NOT NULL,
    [RefItemCode]      VARCHAR (50)    NULL,
    [Uom]              VARCHAR (5)     NOT NULL,
    [BaseUom]          VARCHAR (5)     NOT NULL,
    [UC]               DECIMAL (18, 8) NOT NULL,
    [UCDesc]           VARCHAR (50)    NULL,
    [MinUC]            DECIMAL (18, 8) NOT NULL,
    [StartDate]        DATETIME        NULL,
    [EndDate]          DATETIME        NULL,
    [Bom]              VARCHAR (50)    NULL,
    [LocFrom]          VARCHAR (50)    NULL,
    [LocTo]            VARCHAR (50)    NULL,
    [BillAddr]         VARCHAR (50)    NULL,
    [PriceList]        VARCHAR (50)    NULL,
    [Routing]          VARCHAR (50)    NULL,
    [ReturnRouting]    VARCHAR (50)    NULL,
    [Strategy]         TINYINT         NOT NULL,
    [ProdScan]         VARCHAR (50)    NULL,
    [Container]        VARCHAR (50)    NULL,
    [ContainerDesc]    VARCHAR (50)    NULL,
    [IsAutoCreate]     BIT             NOT NULL,
    [IsInspect]        BIT             NOT NULL,
    [IsRejInspect]     BIT             NOT NULL,
    [SafeStock]        DECIMAL (18, 8) NULL,
    [MaxStock]         DECIMAL (18, 8) NULL,
    [MinLotSize]       DECIMAL (18, 8) NULL,
    [OrderLotSize]     DECIMAL (18, 8) NULL,
    [RecLotSize]       DECIMAL (18, 8) NULL,
    [BatchSize]        DECIMAL (18, 8) NULL,
    [RoundUpOpt]       TINYINT         NOT NULL,
    [BillTerm]         TINYINT         NOT NULL,
    [MrpWeight]        INT             NOT NULL,
    [MrpTotal]         DECIMAL (18, 8) NOT NULL,
    [MrpTotalAdj]      DECIMAL (18, 8) NOT NULL,
    [ExtraDmdSource]   VARCHAR (256)   NULL,
    [PickStrategy]     VARCHAR (50)    NULL,
    [EBELN]            VARCHAR (50)    NULL,
    [EBELP]            VARCHAR (50)    NULL,
    [CreateUser]       INT             NOT NULL,
    [CreateUserNm]     VARCHAR (100)   NOT NULL,
    [CreateDate]       DATETIME        NOT NULL,
    [LastModifyUser]   INT             NOT NULL,
    [LastModifyUserNm] VARCHAR (100)   NOT NULL,
    [LastModifyDate]   DATETIME        NOT NULL,
    [BinTo]            VARCHAR (50)    NULL,
    [IsChangeUC]       BIT             NOT NULL,
    [IsCheckedPackage] BIT             NULL,
    [FreezeDays]       INT             NULL,
    [IsActive]         BIT             NULL,
    [ManufactureParty] VARCHAR (50)    NULL,
    [MrpTag]           VARCHAR (50)    NULL,
    [IsCreatePickList] BIT             NULL
);

