//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Sconit.Service.SAP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.86.128.31:8000/XISOAPAdapter/MessageServlet?channel=:LES01:CC_SOAP2&ver" +
            "sion=3.0&Sender.Service=LES01&Interface=http%3A%2F%2Fwww.sih.cq.cn%2Fsap%2Fmm%2F" +
            "02%5EMI_MARC_OUT")]
        public string com_Sconit_Service_SAP_MI_MARC_OUT_MI_MARC_OUTService {
            get {
                return ((string)(this["com_Sconit_Service_SAP_MI_MARC_OUT_MI_MARC_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.86.128.31:8000/XISOAPAdapter/MessageServlet?channel=:LES01:CC_SOAP1&ver" +
            "sion=3.0&Sender.Service=LES01&Interface=http%3A%2F%2Fwww.sih.cq.cn%2Fsap%2Fmm%2F" +
            "01%5EMI_LFA1_LES")]
        public string com_Sconit_Service_SAP_MI_LFA1_LES_MI_LFA1_LESService {
            get {
                return ((string)(this["com_Sconit_Service_SAP_MI_LFA1_LES_MI_LFA1_LESService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.86.128.31:8000/XISOAPAdapter/MessageServlet?channel=:LES01:CC_SOAP4&ver" +
            "sion=3.0&Sender.Service=LES01&Interface=http%3A%2F%2Fwww.sih.cq.cn%2Fsap%2Fmm%2F" +
            "04%5EMI_QUOTA_OUT")]
        public string com_Sconit_Service_SAP_MI_QUOTA_OUT_MI_QUOTA_OUTService {
            get {
                return ((string)(this["com_Sconit_Service_SAP_MI_QUOTA_OUT_MI_QUOTA_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.86.128.31:8000/XISOAPAdapter/MessageServlet?channel=:LES01:CC_SOAPP3&ve" +
            "rsion=3.0&Sender.Service=LES01&Interface=http%3A%2F%2Fwww.sih.cq.cn%2Fsap%2Fpp%2" +
            "F03%5EMI_PO_CRE_LES")]
        public string com_Sconit_Service_SAP_MI_PO_CRE_LES_MI_PO_CRE_LESService {
            get {
                return ((string)(this["com_Sconit_Service_SAP_MI_PO_CRE_LES_MI_PO_CRE_LESService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.86.128.31:8000/XISOAPAdapter/MessageServlet?channel=:LES01:CC_SOAP5&ver" +
            "sion=3.0&Sender.Service=LES01&Interface=http%3A%2F%2Fwww.sih.cq.cn%2Fsap%2Fmm%2F" +
            "05%5EMI_SL_OUT")]
        public string com_Sconit_Service_SAP_MI_SL_OUT_MI_SL_OUTService {
            get {
                return ((string)(this["com_Sconit_Service_SAP_MI_SL_OUT_MI_SL_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.86.128.31:8000/XISOAPAdapter/MessageServlet?channel=:LES01:CC_SOAP6&ver" +
            "sion=3.0&Sender.Service=LES01&Interface=http%3A%2F%2Fwww.sih.cq.cn%2Fsap%2Fmm%2F" +
            "06%5EMI_EORD_OUT")]
        public string com_Sconit_Service_SAP_MI_EORD_OUT_MI_EORD_OUTService {
            get {
                return ((string)(this["com_Sconit_Service_SAP_MI_EORD_OUT_MI_EORD_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.86.128.31:8000/XISOAPAdapter/MessageServlet?channel=:LES01:CC_SOAPP2&ve" +
            "rsion=3.0&Sender.Service=LES01&Interface=http%3A%2F%2Fwww.sih.cq.cn%2Fsap%2Fpp%2" +
            "F02%5EMI_PO_BOM_LES")]
        public string com_Sconit_Service_SAP_MI_PO_BOM_LES_MI_PO_BOM_LESService {
            get {
                return ((string)(this["com_Sconit_Service_SAP_MI_PO_BOM_LES_MI_PO_BOM_LESService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.86.128.31:8000/XISOAPAdapter/MessageServlet?channel=:LES01:CC_SOAPP4&ve" +
            "rsion=3.0&Sender.Service=LES01&Interface=http%3A%2F%2Fwww.sih.cq.cn%2Fsap%2Fpp%2" +
            "F04%5EMI_PO_CFR_LES")]
        public string com_Sconit_Service_SAP_MI_PO_CFR_LES_MI_PO_CFR_LESService {
            get {
                return ((string)(this["com_Sconit_Service_SAP_MI_PO_CFR_LES_MI_PO_CFR_LESService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.86.128.31:8000/XISOAPAdapter/MessageServlet?channel=:LES01:CC_SOAP3&ver" +
            "sion=3.0&Sender.Service=LES01&Interface=http%3A%2F%2Fwww.sih.cq.cn%2Fsap%2Fmm%2F" +
            "03%5EMI_LES")]
        public string com_Sconit_Service_SAP_MI_LES_MI_LESService {
            get {
                return ((string)(this["com_Sconit_Service_SAP_MI_LES_MI_LESService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.86.128.31:8000/XISOAPAdapter/MessageServlet?channel=:LES01:CC_SOAPP7&ve" +
            "rsion=3.0&Sender.Service=LES01&Interface=http%3A%2F%2Fwww.sih.cq.cn%2Fsap%2Fpp%2" +
            "F07%5EMI_POFIX_LES")]
        public string com_Sconit_Service_SAP_MI_POFIX_LES_MI_POFIX_LESService {
            get {
                return ((string)(this["com_Sconit_Service_SAP_MI_POFIX_LES_MI_POFIX_LESService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.86.128.63:8000/XISOAPAdapter/MessageServlet?channel=:LES01:CC_SOAPS2&ve" +
            "rsion=3.0&Sender.Service=MI_LES2SAP_POST_DELIV_DOCService&Interface=http%3A%2F%2" +
            "Fwww.sih.cq.cn%2Fsap%2Fsd%2F01%2Fles%5EMI_LES2SAP_POST_DELIV_DOC")]
        public string com_Sconit_Service_SAP_MI_LES2SAP_POST_DELIV_DOC_MI_LES2SAP_POST_DELIV_DOCService {
            get {
                return ((string)(this["com_Sconit_Service_SAP_MI_LES2SAP_POST_DELIV_DOC_MI_LES2SAP_POST_DELIV_DOCService" +
                    ""]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.86.128.31:8000/XISOAPAdapter/MessageServlet?channel=:LES01:CC_SOAP7&ver" +
            "sion=3.0&Sender.Service=LES01&Interface=http%3A%2F%2Fwww.sih.cq.cn%2Fsap%2Fmm%2F" +
            "07%5EMI_CRSL_LES")]
        public string com_Sconit_Service_SAP_MI_CRSL_LES1_MI_CRSL_LESService {
            get {
                return ((string)(this["com_Sconit_Service_SAP_MI_CRSL_LES1_MI_CRSL_LESService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.86.128.31:8000/XISOAPAdapter/MessageServlet?channel=:LES01:CC_SOAPP5&ve" +
            "rsion=3.0&Sender.Service=LES01&Interface=http%3A%2F%2Fwww.sih.cq.cn%2Fsap%2Fpp%2" +
            "F05%5EMI_POIF_LES")]
        public string com_Sconit_Service_SAP_MI_POIF_LES_MI_POIF_LESService {
            get {
                return ((string)(this["com_Sconit_Service_SAP_MI_POIF_LES_MI_POIF_LESService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.86.128.31:8000/XISOAPAdapter/MessageServlet?channel=:LES01:CC_SOAPP1&ve" +
            "rsion=3.0&Sender.Service=LES01&Interface=http%3A%2F%2Fwww.sih.cq.cn%2Fsap%2Fpp%2" +
            "F01%5EMI_PO_HEAD_LES")]
        public string com_Sconit_Service_SAP_MI_PO_HEAD_LES_MI_PO_HEAD_LESService {
            get {
                return ((string)(this["com_Sconit_Service_SAP_MI_PO_HEAD_LES_MI_PO_HEAD_LESService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.86.128.31:8000/XISOAPAdapter/MessageServlet?channel=:LES01:CC_SOAPP8&ve" +
            "rsion=3.0&Sender.Service=LES01&Interface=http%3A%2F%2Fwww.sih.cq.cn%2Fsap%2Fpp%2" +
            "F08%5EMI_POCANCLE_LES")]
        public string com_Sconit_Service_SAP_MI_POCANCLE_LES_MI_POCANCLE_LESService {
            get {
                return ((string)(this["com_Sconit_Service_SAP_MI_POCANCLE_LES_MI_POCANCLE_LESService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.86.128.63:8000/XISOAPAdapter/MessageServlet?channel=:LES01:CC_SOAP8&ver" +
            "sion=3.0&Sender.Service=LES01&Interface=http%3A%2F%2Fwww.sih.cq.cn%2Fsap%2Fmm%2F" +
            "08%5EMI_NQC_LES")]
        public string com_Sconit_Service_SAP_MI_NQC_LES_MI_NQC_LESService {
            get {
                return ((string)(this["com_Sconit_Service_SAP_MI_NQC_LES_MI_NQC_LESService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.86.128.31:8000/XISOAPAdapter/MessageServlet?channel=:LES01:CC_SOAPP9&ve" +
            "rsion=3.0&Sender.Service=LES01&Interface=http%3A%2F%2Fwww.sih.cq.cn%2Fsap%2Fpp%2" +
            "F09%5EMI_PO_LES")]
        public string com_Sconit_Service_SAP_MI_PO_LES_MI_PO_LESService {
            get {
                return ((string)(this["com_Sconit_Service_SAP_MI_PO_LES_MI_PO_LESService"]));
            }
        }
    }
}
