//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace com.Sconit.Service.SAP.MI_LFA1_LES {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MI_LFA1_LESBinding", Namespace="http://www.sih.cq.cn/sap/mm/01")]
    public partial class MI_LFA1_LESService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MI_LFA1_LESOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MI_LFA1_LESService() {
            this.Url = global::com.Sconit.Service.SAP.Properties.Settings.Default.com_Sconit_Service_SAP_MI_LFA1_LES_MI_LFA1_LESService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MI_LFA1_LESCompletedEventHandler MI_LFA1_LESCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("MT_LES", Namespace="http://www.sih.cq.cn/sap/mm/01")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_LESITEM[] MI_LFA1_LES([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.sih.cq.cn/sap/mm/01")] DT_SAP MT_SAP) {
            object[] results = this.Invoke("MI_LFA1_LES", new object[] {
                        MT_SAP});
            return ((DT_LESITEM[])(results[0]));
        }
        
        /// <remarks/>
        public void MI_LFA1_LESAsync(DT_SAP MT_SAP) {
            this.MI_LFA1_LESAsync(MT_SAP, null);
        }
        
        /// <remarks/>
        public void MI_LFA1_LESAsync(DT_SAP MT_SAP, object userState) {
            if ((this.MI_LFA1_LESOperationCompleted == null)) {
                this.MI_LFA1_LESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMI_LFA1_LESOperationCompleted);
            }
            this.InvokeAsync("MI_LFA1_LES", new object[] {
                        MT_SAP}, this.MI_LFA1_LESOperationCompleted, userState);
        }
        
        private void OnMI_LFA1_LESOperationCompleted(object arg) {
            if ((this.MI_LFA1_LESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MI_LFA1_LESCompleted(this, new MI_LFA1_LESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sih.cq.cn/sap/mm/01")]
    public partial class DT_SAP {
        
        private string iNPUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INPUT {
            get {
                return this.iNPUTField;
            }
            set {
                this.iNPUTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sih.cq.cn/sap/mm/01")]
    public partial class DT_LESITEM {
        
        private string supplierCodeField;
        
        private string oldsupplierCodeField;
        
        private string supplierNameField;
        
        private string shipFromAddrField;
        
        private string shipFromTelField;
        
        private string shipFromFaxField;
        
        private string shipFromContactField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string supplierCode {
            get {
                return this.supplierCodeField;
            }
            set {
                this.supplierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string oldsupplierCode {
            get {
                return this.oldsupplierCodeField;
            }
            set {
                this.oldsupplierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string supplierName {
            get {
                return this.supplierNameField;
            }
            set {
                this.supplierNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipFromAddr {
            get {
                return this.shipFromAddrField;
            }
            set {
                this.shipFromAddrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipFromTel {
            get {
                return this.shipFromTelField;
            }
            set {
                this.shipFromTelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipFromFax {
            get {
                return this.shipFromFaxField;
            }
            set {
                this.shipFromFaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipFromContact {
            get {
                return this.shipFromContactField;
            }
            set {
                this.shipFromContactField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MI_LFA1_LESCompletedEventHandler(object sender, MI_LFA1_LESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MI_LFA1_LESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MI_LFA1_LESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_LESITEM[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_LESITEM[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591