//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormTest.SessionReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetail", Namespace="http://schemas.datacontract.org/2004/07/com.Sconit.SDEntity")]
    [System.SerializableAttribute()]
    public partial class OrderDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal CurrentReceiveQtyk__BackingFieldField;
        
        private decimal CurrentShipQtyk__BackingFieldField;
        
        private int Idk__BackingFieldField;
        
        private string ItemDescriptionk__BackingFieldField;
        
        private string Itemk__BackingFieldField;
        
        private string OrderNok__BackingFieldField;
        
        private string ReferenceItemCodek__BackingFieldField;
        
        private decimal RemainReceivedQtyk__BackingFieldField;
        
        private decimal RemainShippedQtyk__BackingFieldField;
        
        private int Sequencek__BackingFieldField;
        
        private decimal UnitCountk__BackingFieldField;
        
        private string Uomk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CurrentReceiveQty>k__BackingField", IsRequired=true)]
        public decimal CurrentReceiveQtyk__BackingField {
            get {
                return this.CurrentReceiveQtyk__BackingFieldField;
            }
            set {
                if ((this.CurrentReceiveQtyk__BackingFieldField.Equals(value) != true)) {
                    this.CurrentReceiveQtyk__BackingFieldField = value;
                    this.RaisePropertyChanged("CurrentReceiveQtyk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CurrentShipQty>k__BackingField", IsRequired=true)]
        public decimal CurrentShipQtyk__BackingField {
            get {
                return this.CurrentShipQtyk__BackingFieldField;
            }
            set {
                if ((this.CurrentShipQtyk__BackingFieldField.Equals(value) != true)) {
                    this.CurrentShipQtyk__BackingFieldField = value;
                    this.RaisePropertyChanged("CurrentShipQtyk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Id>k__BackingField", IsRequired=true)]
        public int Idk__BackingField {
            get {
                return this.Idk__BackingFieldField;
            }
            set {
                if ((this.Idk__BackingFieldField.Equals(value) != true)) {
                    this.Idk__BackingFieldField = value;
                    this.RaisePropertyChanged("Idk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ItemDescription>k__BackingField", IsRequired=true)]
        public string ItemDescriptionk__BackingField {
            get {
                return this.ItemDescriptionk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDescriptionk__BackingFieldField, value) != true)) {
                    this.ItemDescriptionk__BackingFieldField = value;
                    this.RaisePropertyChanged("ItemDescriptionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Item>k__BackingField", IsRequired=true)]
        public string Itemk__BackingField {
            get {
                return this.Itemk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Itemk__BackingFieldField, value) != true)) {
                    this.Itemk__BackingFieldField = value;
                    this.RaisePropertyChanged("Itemk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OrderNo>k__BackingField", IsRequired=true)]
        public string OrderNok__BackingField {
            get {
                return this.OrderNok__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNok__BackingFieldField, value) != true)) {
                    this.OrderNok__BackingFieldField = value;
                    this.RaisePropertyChanged("OrderNok__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ReferenceItemCode>k__BackingField", IsRequired=true)]
        public string ReferenceItemCodek__BackingField {
            get {
                return this.ReferenceItemCodek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceItemCodek__BackingFieldField, value) != true)) {
                    this.ReferenceItemCodek__BackingFieldField = value;
                    this.RaisePropertyChanged("ReferenceItemCodek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<RemainReceivedQty>k__BackingField", IsRequired=true)]
        public decimal RemainReceivedQtyk__BackingField {
            get {
                return this.RemainReceivedQtyk__BackingFieldField;
            }
            set {
                if ((this.RemainReceivedQtyk__BackingFieldField.Equals(value) != true)) {
                    this.RemainReceivedQtyk__BackingFieldField = value;
                    this.RaisePropertyChanged("RemainReceivedQtyk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<RemainShippedQty>k__BackingField", IsRequired=true)]
        public decimal RemainShippedQtyk__BackingField {
            get {
                return this.RemainShippedQtyk__BackingFieldField;
            }
            set {
                if ((this.RemainShippedQtyk__BackingFieldField.Equals(value) != true)) {
                    this.RemainShippedQtyk__BackingFieldField = value;
                    this.RaisePropertyChanged("RemainShippedQtyk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Sequence>k__BackingField", IsRequired=true)]
        public int Sequencek__BackingField {
            get {
                return this.Sequencek__BackingFieldField;
            }
            set {
                if ((this.Sequencek__BackingFieldField.Equals(value) != true)) {
                    this.Sequencek__BackingFieldField = value;
                    this.RaisePropertyChanged("Sequencek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UnitCount>k__BackingField", IsRequired=true)]
        public decimal UnitCountk__BackingField {
            get {
                return this.UnitCountk__BackingFieldField;
            }
            set {
                if ((this.UnitCountk__BackingFieldField.Equals(value) != true)) {
                    this.UnitCountk__BackingFieldField = value;
                    this.RaisePropertyChanged("UnitCountk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Uom>k__BackingField", IsRequired=true)]
        public string Uomk__BackingField {
            get {
                return this.Uomk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Uomk__BackingFieldField, value) != true)) {
                    this.Uomk__BackingFieldField = value;
                    this.RaisePropertyChanged("Uomk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hu", Namespace="http://schemas.datacontract.org/2004/07/com.Sconit.SDEntity")]
    [System.SerializableAttribute()]
    public partial class Hu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal CurrentQtyk__BackingFieldField;
        
        private int DetailIdk__BackingFieldField;
        
        private string HuIdk__BackingFieldField;
        
        private string HuTemplatek__BackingFieldField;
        
        private string ItemDescriptionk__BackingFieldField;
        
        private string Itemk__BackingFieldField;
        
        private string LocationBink__BackingFieldField;
        
        private string Locationk__BackingFieldField;
        
        private string LotNok__BackingFieldField;
        
        private System.DateTime ManufactureDatek__BackingFieldField;
        
        private string ManufacturePartyk__BackingFieldField;
        
        private short PrintCountk__BackingFieldField;
        
        private decimal Qtyk__BackingFieldField;
        
        private string Statusk__BackingFieldField;
        
        private decimal UnitQtyk__BackingFieldField;
        
        private string Uomk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CurrentQty>k__BackingField", IsRequired=true)]
        public decimal CurrentQtyk__BackingField {
            get {
                return this.CurrentQtyk__BackingFieldField;
            }
            set {
                if ((this.CurrentQtyk__BackingFieldField.Equals(value) != true)) {
                    this.CurrentQtyk__BackingFieldField = value;
                    this.RaisePropertyChanged("CurrentQtyk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DetailId>k__BackingField", IsRequired=true)]
        public int DetailIdk__BackingField {
            get {
                return this.DetailIdk__BackingFieldField;
            }
            set {
                if ((this.DetailIdk__BackingFieldField.Equals(value) != true)) {
                    this.DetailIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("DetailIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<HuId>k__BackingField", IsRequired=true)]
        public string HuIdk__BackingField {
            get {
                return this.HuIdk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.HuIdk__BackingFieldField, value) != true)) {
                    this.HuIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("HuIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<HuTemplate>k__BackingField", IsRequired=true)]
        public string HuTemplatek__BackingField {
            get {
                return this.HuTemplatek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.HuTemplatek__BackingFieldField, value) != true)) {
                    this.HuTemplatek__BackingFieldField = value;
                    this.RaisePropertyChanged("HuTemplatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ItemDescription>k__BackingField", IsRequired=true)]
        public string ItemDescriptionk__BackingField {
            get {
                return this.ItemDescriptionk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDescriptionk__BackingFieldField, value) != true)) {
                    this.ItemDescriptionk__BackingFieldField = value;
                    this.RaisePropertyChanged("ItemDescriptionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Item>k__BackingField", IsRequired=true)]
        public string Itemk__BackingField {
            get {
                return this.Itemk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Itemk__BackingFieldField, value) != true)) {
                    this.Itemk__BackingFieldField = value;
                    this.RaisePropertyChanged("Itemk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LocationBin>k__BackingField", IsRequired=true)]
        public string LocationBink__BackingField {
            get {
                return this.LocationBink__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationBink__BackingFieldField, value) != true)) {
                    this.LocationBink__BackingFieldField = value;
                    this.RaisePropertyChanged("LocationBink__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Location>k__BackingField", IsRequired=true)]
        public string Locationk__BackingField {
            get {
                return this.Locationk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Locationk__BackingFieldField, value) != true)) {
                    this.Locationk__BackingFieldField = value;
                    this.RaisePropertyChanged("Locationk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LotNo>k__BackingField", IsRequired=true)]
        public string LotNok__BackingField {
            get {
                return this.LotNok__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LotNok__BackingFieldField, value) != true)) {
                    this.LotNok__BackingFieldField = value;
                    this.RaisePropertyChanged("LotNok__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ManufactureDate>k__BackingField", IsRequired=true)]
        public System.DateTime ManufactureDatek__BackingField {
            get {
                return this.ManufactureDatek__BackingFieldField;
            }
            set {
                if ((this.ManufactureDatek__BackingFieldField.Equals(value) != true)) {
                    this.ManufactureDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("ManufactureDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ManufactureParty>k__BackingField", IsRequired=true)]
        public string ManufacturePartyk__BackingField {
            get {
                return this.ManufacturePartyk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturePartyk__BackingFieldField, value) != true)) {
                    this.ManufacturePartyk__BackingFieldField = value;
                    this.RaisePropertyChanged("ManufacturePartyk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PrintCount>k__BackingField", IsRequired=true)]
        public short PrintCountk__BackingField {
            get {
                return this.PrintCountk__BackingFieldField;
            }
            set {
                if ((this.PrintCountk__BackingFieldField.Equals(value) != true)) {
                    this.PrintCountk__BackingFieldField = value;
                    this.RaisePropertyChanged("PrintCountk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Qty>k__BackingField", IsRequired=true)]
        public decimal Qtyk__BackingField {
            get {
                return this.Qtyk__BackingFieldField;
            }
            set {
                if ((this.Qtyk__BackingFieldField.Equals(value) != true)) {
                    this.Qtyk__BackingFieldField = value;
                    this.RaisePropertyChanged("Qtyk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Status>k__BackingField", IsRequired=true)]
        public string Statusk__BackingField {
            get {
                return this.Statusk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Statusk__BackingFieldField, value) != true)) {
                    this.Statusk__BackingFieldField = value;
                    this.RaisePropertyChanged("Statusk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UnitQty>k__BackingField", IsRequired=true)]
        public decimal UnitQtyk__BackingField {
            get {
                return this.UnitQtyk__BackingFieldField;
            }
            set {
                if ((this.UnitQtyk__BackingFieldField.Equals(value) != true)) {
                    this.UnitQtyk__BackingFieldField = value;
                    this.RaisePropertyChanged("UnitQtyk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Uom>k__BackingField", IsRequired=true)]
        public string Uomk__BackingField {
            get {
                return this.Uomk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Uomk__BackingFieldField, value) != true)) {
                    this.Uomk__BackingFieldField = value;
                    this.RaisePropertyChanged("Uomk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://com.Sconit.SDService", ConfigurationName="SessionReference.IIpService")]
    public interface IIpService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.Sconit.SDService/IIpService/ScanOrderNo", ReplyAction="http://com.Sconit.SDService/IIpService/ScanOrderNoResponse")]
        FormTest.SessionReference.OrderDetail[] ScanOrderNo(string orderNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.Sconit.SDService/IIpService/ScanHu", ReplyAction="http://com.Sconit.SDService/IIpService/ScanHuResponse")]
        int ScanHu(string huId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.Sconit.SDService/IIpService/CancelHu", ReplyAction="http://com.Sconit.SDService/IIpService/CancelHuResponse")]
        string CancelHu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.Sconit.SDService/IIpService/GetHu", ReplyAction="http://com.Sconit.SDService/IIpService/GetHuResponse")]
        FormTest.SessionReference.Hu GetHu(string huId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIpServiceChannel : FormTest.SessionReference.IIpService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IpServiceClient : System.ServiceModel.ClientBase<FormTest.SessionReference.IIpService>, FormTest.SessionReference.IIpService {
        
        public IpServiceClient() {
        }
        
        public IpServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IpServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IpServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IpServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FormTest.SessionReference.OrderDetail[] ScanOrderNo(string orderNo) {
            return base.Channel.ScanOrderNo(orderNo);
        }
        
        public int ScanHu(string huId) {
            return base.Channel.ScanHu(huId);
        }
        
        public string CancelHu() {
            return base.Channel.CancelHu();
        }
        
        public FormTest.SessionReference.Hu GetHu(string huId) {
            return base.Channel.GetHu(huId);
        }
    }
}
