//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1008.
// 
#pragma warning disable 1591

namespace com.Sconit.Service.SAP.MI_LES2SAP_POST_DELIV_DOC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MI_LES2SAP_POST_DELIV_DOCBinding", Namespace="http://www.sih.cq.cn/sap/sd/01/les")]
    public partial class MI_LES2SAP_POST_DELIV_DOCService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MI_LES2SAP_POST_DELIV_DOCOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MI_LES2SAP_POST_DELIV_DOCService() {
            this.Url = global::com.Sconit.Service.SAP.Properties.Settings.Default.com_Sconit_Service_SAP_MI_LES2SAP_POST_DELIV_DOC_MI_LES2SAP_POST_DELIV_DOCService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MI_LES2SAP_POST_DELIV_DOCCompletedEventHandler MI_LES2SAP_POST_DELIV_DOCCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", RequestElementName="ZSD_RCV_POST_DELIV_DOC", RequestNamespace="urn:sap-com:document:sap:rfc:functions", ResponseElementName="ZSD_RCV_POST_DELIV_DOC.Response", ResponseNamespace="urn:sap-com:document:sap:rfc:functions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("MESSAGE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MI_LES2SAP_POST_DELIV_DOC([System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] ref ZSTM_ZSDDNFLES[] DELIV_DOCS, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string SUCCESS) {
            object[] results = this.Invoke("MI_LES2SAP_POST_DELIV_DOC", new object[] {
                        DELIV_DOCS});
            DELIV_DOCS = ((ZSTM_ZSDDNFLES[])(results[1]));
            SUCCESS = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MI_LES2SAP_POST_DELIV_DOCAsync(ZSTM_ZSDDNFLES[] DELIV_DOCS) {
            this.MI_LES2SAP_POST_DELIV_DOCAsync(DELIV_DOCS, null);
        }
        
        /// <remarks/>
        public void MI_LES2SAP_POST_DELIV_DOCAsync(ZSTM_ZSDDNFLES[] DELIV_DOCS, object userState) {
            if ((this.MI_LES2SAP_POST_DELIV_DOCOperationCompleted == null)) {
                this.MI_LES2SAP_POST_DELIV_DOCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMI_LES2SAP_POST_DELIV_DOCOperationCompleted);
            }
            this.InvokeAsync("MI_LES2SAP_POST_DELIV_DOC", new object[] {
                        DELIV_DOCS}, this.MI_LES2SAP_POST_DELIV_DOCOperationCompleted, userState);
        }
        
        private void OnMI_LES2SAP_POST_DELIV_DOCOperationCompleted(object arg) {
            if ((this.MI_LES2SAP_POST_DELIV_DOCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MI_LES2SAP_POST_DELIV_DOCCompleted(this, new MI_LES2SAP_POST_DELIV_DOCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSTM_ZSDDNFLES {
        
        private string vBELNField;
        
        private string pOSNRField;
        
        private string zTCODEField;
        
        private string mATNRField;
        
        private string wERKSField;
        
        private string lGORTField;
        
        private decimal pIKMGField;
        
        private bool pIKMGFieldSpecified;
        
        private string vRKMEField;
        
        private string wADAT_ISTField;
        
        private string wMSNRField;
        
        private string wMSPONRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VBELN {
            get {
                return this.vBELNField;
            }
            set {
                this.vBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POSNR {
            get {
                return this.pOSNRField;
            }
            set {
                this.pOSNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZTCODE {
            get {
                return this.zTCODEField;
            }
            set {
                this.zTCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LGORT {
            get {
                return this.lGORTField;
            }
            set {
                this.lGORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PIKMG {
            get {
                return this.pIKMGField;
            }
            set {
                this.pIKMGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PIKMGSpecified {
            get {
                return this.pIKMGFieldSpecified;
            }
            set {
                this.pIKMGFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VRKME {
            get {
                return this.vRKMEField;
            }
            set {
                this.vRKMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WADAT_IST {
            get {
                return this.wADAT_ISTField;
            }
            set {
                this.wADAT_ISTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WMSNR {
            get {
                return this.wMSNRField;
            }
            set {
                this.wMSNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WMSPONR {
            get {
                return this.wMSPONRField;
            }
            set {
                this.wMSPONRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MI_LES2SAP_POST_DELIV_DOCCompletedEventHandler(object sender, MI_LES2SAP_POST_DELIV_DOCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MI_LES2SAP_POST_DELIV_DOCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MI_LES2SAP_POST_DELIV_DOCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ZSTM_ZSDDNFLES[] DELIV_DOCS {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZSTM_ZSDDNFLES[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string SUCCESS {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591