CREATE PROCEDURE [dbo].[USP_Split_OrderMstr_UPDATE]
@Version INT, @Flow VARCHAR (50), @FlowDesc VARCHAR (50), @TraceCode VARCHAR (50), @RefOrderNo VARCHAR (50), @ExtOrderNo VARCHAR (50), @Type TINYINT, @SubType TINYINT, @QualityType TINYINT, @StartTime DATETIME, @WindowTime DATETIME, @PauseStatus TINYINT, @PauseSeq INT, @PauseTime DATETIME, @EffDate DATETIME, @Priority TINYINT, @Status TINYINT, @PartyFrom VARCHAR (50), @PartyFromNm VARCHAR (100), @PartyTo VARCHAR (50), @PartyToNm VARCHAR (100), @ShipFrom VARCHAR (50), @ShipFromAddr VARCHAR (256), @ShipFromTel VARCHAR (50), @ShipFromCell VARCHAR (50), @ShipFromFax VARCHAR (50), @ShipFromContact VARCHAR (50), @ShipToAddr VARCHAR (256), @ShipTo VARCHAR (50), @ShipToTel VARCHAR (50), @ShipToCell VARCHAR (50), @ShipToFax VARCHAR (50), @ShipToContact VARCHAR (50), @Shift VARCHAR (50), @LocFrom VARCHAR (50), @LocFromNm VARCHAR (100), @LocTo VARCHAR (50), @LocToNm VARCHAR (100), @IsInspect BIT, @BillAddr VARCHAR (50), @BillAddrDesc VARCHAR (256), @PriceList VARCHAR (50), @Currency VARCHAR (50), @Dock VARCHAR (100), @Routing VARCHAR (50), @CurtOp INT, @IsAutoRelease BIT, @IsAutoStart BIT, @IsAutoShip BIT, @IsAutoReceive BIT, @IsAutoBill BIT, @IsManualCreateDet BIT, @IsListPrice BIT, @IsPrintOrder BIT, @IsOrderPrinted BIT, @IsPrintAsn BIT, @IsPrintRec BIT, @IsShipExceed BIT, @IsRecExceed BIT, @IsOrderFulfillUC BIT, @IsShipFulfillUC BIT, @IsRecFulfillUC BIT, @IsShipScanHu BIT, @IsRecScanHu BIT, @IsCreatePL BIT, @IsPLCreate BIT, @IsShipFifo BIT, @IsRecFifo BIT, @IsShipByOrder BIT, @IsOpenOrder BIT, @IsAsnUniqueRec BIT, @RecGapTo TINYINT, @RecTemplate VARCHAR (100), @OrderTemplate VARCHAR (100), @AsnTemplate VARCHAR (100), @HuTemplate VARCHAR (100), @BillTerm TINYINT, @CreateHuOpt TINYINT, @ReCalculatePriceOpt TINYINT, @WMSNo VARCHAR (50), @LastModifyUser INT, @LastModifyUserNm VARCHAR (100), @LastModifyDate DATETIME, @ReleaseDate DATETIME, @ReleaseUser INT, @ReleaseUserNm VARCHAR (100), @StartDate DATETIME, @StartUser INT, @StartUserNm VARCHAR (100), @CompleteDate DATETIME, @CompleteUser INT, @CompleteUserNm VARCHAR (100), @CloseDate DATETIME, @CloseUser INT, @CloseUserNm VARCHAR (100), @CancelDate DATETIME, @CancelUser INT, @CancelUserNm VARCHAR (100), @CancelReason VARCHAR (256), @OrderStrategy TINYINT, @ProdLineFact VARCHAR (50), @IsQuick BIT, @PickStrategy VARCHAR (50), @ExtraDmdSource VARCHAR (256), @ProdLineType TINYINT, @SeqGroup VARCHAR (50), @OrderNo VARCHAR (4000), @VersionBerfore INT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


